import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { getPhotoUrl } from '../../utils/photoUrl';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Card } from '../ui/card';
import { Lightbox } from '../ui/lightbox';
export const MenuItemCard = ({ item, quantity, onQuantityChange }) => {
    const [lightboxOpen, setLightboxOpen] = useState(false);
    const photoSrc = getPhotoUrl(item.photoUrl);
    return (_jsxs(Card, { className: "space-y-4 p-4", children: [photoSrc ? (_jsxs(_Fragment, { children: [_jsxs("button", { type: "button", onClick: () => setLightboxOpen(true), className: "group relative w-full overflow-hidden rounded-2xl", children: [_jsx("img", { src: photoSrc, alt: item.name, className: "h-40 w-full object-cover transition-transform duration-200 group-hover:scale-[1.03]" }), _jsx("div", { className: "absolute inset-0 flex items-center justify-center bg-black/0 transition-colors group-hover:bg-black/20 rounded-2xl", children: _jsx("svg", { className: "h-8 w-8 text-white opacity-0 drop-shadow group-hover:opacity-100 transition-opacity", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1.5, d: "M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5v-4m0 4h-4m4 0l-5-5" }) }) })] }), lightboxOpen && (_jsx(Lightbox, { src: photoSrc, alt: item.name, onClose: () => setLightboxOpen(false) }))] })) : (_jsx("div", { className: "flex h-40 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 text-sm text-slate-400", children: "No image" })), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-slate-900", children: item.name || 'Menu Item' }), _jsx("p", { className: "text-sm uppercase tracking-[0.2em] text-slate-500", children: (item.category ? item.category.replace(/_/g, ' ') : 'General') })] }), _jsxs("div", { className: "text-right text-lg font-semibold text-slate-900", children: ["$", (Number(item.priceCents ?? 0) / 100).toFixed(2)] })] }), item.description ? (_jsx("p", { className: "text-sm leading-6 text-slate-600", children: item.description })) : null] }), _jsxs("div", { className: "grid gap-3", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-700", children: "Qty" }), _jsx(Input, { type: "number", min: 0, value: quantity, onChange: (event) => onQuantityChange(Number(event.target.value)), className: "w-full" })] }), _jsx(Button, { variant: quantity > 0 ? 'accent' : 'secondary', onClick: () => onQuantityChange(quantity > 0 ? 0 : 1), children: quantity > 0 ? 'Remove' : 'Add' })] })] }));
};
