export type Locale = 'en' | 'ru' | 'uz';

export const locales: Locale[] = ['en', 'ru', 'uz'];

export const defaultLocale: Locale = 'uz';

const resources = {
  en: {
    banquet_admin: 'Banquet Admin',
    events: 'Events',
    menu: 'Menu',
    tables: 'Tables',
    halls: 'Halls',
    tablet: 'Tablet',
    logout: 'Log out',
    logging_out: 'Logging out...',
    client_menu_selection: 'Client Menu Selection',
    room_table_settings: 'Room & Table Settings',
    select_room: 'Select Room',
    select_table_category: 'Select Table Category',
    guests: 'Guests',
    choose_room: 'Choose a room...',
    choose_table_category: 'Choose a table category...',
    selected: 'Selected',
    loading_menu: 'Loading menu...',
    failed_load_menu: 'Failed to load menu.',
    real_time_estimate: 'Real-time estimate',
    per_guest: 'Per guest',
    view_summary: 'View Summary',
    selection_summary: 'Selection Summary',
    customer_details: 'Customer Details',
    customer_name: 'Name',
    customer_phone: 'Phone',
    event_details: 'Event Details',
    hall: 'Hall',
    table_category: 'Table Category',
    guest_count: 'Guest Count',
    selected_dishes: 'Selected Dishes',
    pricing: 'Pricing',
    subtotal: 'Subtotal',
    service_fee: 'Service Fee',
    tax: 'Tax',
    total: 'Total',
    price_per_person: 'Price per Person',
    summary: 'Summary',
    thank_you: 'Thank you for choosing our banquet services. Your selection has been recorded.',
    total_guests: 'Total guests',
    estimated_total: 'Estimated total',
    edit_selection: 'Edit Selection',
    confirm: 'Confirm',
    download_pdf: 'Download PDF',
    download_excel: 'Download Excel',
    language: 'Language',
    english: 'English',
    russian: 'Русский',
    uzbek: 'O‘zbekcha',
    banquet_events: 'Banquet Events',
    create_new_event: 'Create new event',
    edit_existing_event: 'Edit existing event',
    phone_number: 'Phone Number',
    event_date_time: 'Event date/time',
    event_type: 'Event Type',
    status: 'Status',
    hall_optional: 'Hall (Optional)',
    table_category_optional: 'Table category (Optional)',
    notes: 'Notes',
    create_event: 'Create event',
    creating: 'Creating...',
    update_event: 'Update event',
    updating: 'Updating...',
    cancel: 'Cancel',
    loading_events: 'Loading events...',
    failed_load_events: 'Failed to load events.',
    select_hall: '-- Select a hall --',
    menu_management: 'Menu Management',
    create_menu_item: 'Create Menu Item',
    name: 'Name',
    description: 'Description',
    category: 'Category',
    price: 'Price',
    photo_url: 'Photo URL',
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    deleting: 'Deleting...',
    active: 'Active',
    inactive: 'Inactive',
    hot_appetizers: 'Hot Appetizers',
    first_course: 'First Course',
    second_course: 'Second Course',
    table_categories_management: 'Table Categories Management',
    create_table_category: 'Create Table Category',
    seating_capacity: 'Seating Capacity',
    meal_package: 'Meal Package',
    rate_per_person: 'Rate per Person',
    table_category_name_placeholder: 'e.g., 2-person table',
    photo_url_optional: 'Photo URL (Optional)',
    description_optional: 'Description (Optional)',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Create category',
    failed_to_create_category: 'Failed to create category.',
    loading_table_categories: 'Loading table categories...',
    failed_to_load_table_categories: 'Failed to load table categories.',
    all_categories: 'All Categories',
    no_table_categories_yet: 'No table categories yet.',
    capacity: 'Capacity',
    meal: 'Meal',
    rate: 'Rate',
    rate_dollar: 'Rate ($)',
    saving: 'Saving...',
    save: 'Save',
    edit: 'Edit',
    halls_management: 'Halls Management',
    create_hall: 'Create Hall',
    hall_name_placeholder: 'e.g., Main Hall',
    create_hall_button: 'Create hall',
    failed_to_create_hall: 'Failed to create hall.',
    loading_halls: 'Loading halls...',
    failed_to_load_halls: 'Failed to load halls.',
    all_halls: 'All Halls',
    no_halls_yet: 'No halls yet.',
    hall_capacity: 'Capacity',
    hall_description: 'Description',
    hall_photo_url: 'Photo URL',
    hall_active: 'Active',
    hall_inactive: 'Inactive'
  },
  ru: {
    banquet_admin: 'Админ Банкет',
    events: 'События',
    menu: 'Меню',
    tables: 'Столы',
    halls: 'Залы',
    tablet: 'Планшет',
    logout: 'Выйти',
    logging_out: 'Выход...',
    client_menu_selection: 'Выбор меню клиента',
    room_table_settings: 'Нastройки зала и столов',
    select_room: 'Выбрать зал',
    select_table_category: 'Выбрать категорию стола',
    guests: 'Гостей',
    choose_room: 'Выберите зал...',
    choose_table_category: 'Выберите категорию стола...',
    selected: 'Выбрано',
    loading_menu: 'Загрузка меню...',
    failed_load_menu: 'Не удалось загрузить меню.',
    real_time_estimate: 'Оценка в реальном времени',
    service_fee: 'Сервисный сбор',
    per_guest: 'На гостя',
    view_summary: 'Просмотреть итоги',
    selection_summary: 'Итоговый выбор',
    customer_details: 'Данные клиента',
    customer_name: 'Имя',
    customer_phone: 'Телефон',
    event_details: 'Данные мероприятия',
    hall: 'Зал',
    table_category: 'Категория стола',
    guest_count: 'Количество гостей',
    selected_dishes: 'Выбранные блюда',
    pricing: 'Ценообразование',
    subtotal: 'Промежуточный итог',
    tax: 'Налог',
    total: 'Итого',
    price_per_person: 'Цена на человека',
    summary: 'Итог',
    thank_you: 'Спасибо за выбор наших банкетных услуг. Ваш выбор был зафиксирован.',
    total_guests: 'Всего гостей',
    estimated_total: 'Ориентировочная сумма',
    edit_selection: 'Редактировать выбор',
    confirm: 'Подтвердить',
    download_pdf: 'Скачать PDF',
    download_excel: 'Скачать Excel',
    language: 'Язык',
    english: 'English',
    russian: 'Русский',
    uzbek: 'O‘zbekcha',
    banquet_events: 'Банкетные события',
    create_new_event: 'Создать новое событие',
    edit_existing_event: 'Редактировать существующее событие',
    phone_number: 'Номер телефона',
    event_date_time: 'Дата/время события',
    event_type: 'Тип события',
    status: 'Статус',
    hall_optional: 'Зал (Необязательно)',
    table_category_optional: 'Категория стола (Необязательно)',
    notes: 'Заметки',
    create_event: 'Создать событие',
    creating: 'Создание...',
    update_event: 'Обновить событие',
    updating: 'Обновление...',
    cancel: 'Отмена',
    loading_events: 'Загрузка событий...',
    failed_load_events: 'Не удалось загрузить события.',
    select_hall: '-- Выберите зал --',
    menu_management: 'Управление меню',
    create_menu_item: 'Создать пункт меню',
    name: 'Название',
    description: 'Описание',
    category: 'Категория',
    price: 'Цена',
    photo_url: 'URL фото',
    create: 'Создать',
    update: 'Обновить',
    delete: 'Удалить',
    deleting: 'Удаление...',
    active: 'Активен',
    inactive: 'Неактивен',
    hot_appetizers: 'Горячие закуски',
    first_course: 'Первое блюдо',
    second_course: 'Второе блюдо',
    table_categories_management: 'Управление категориями столов',
    create_table_category: 'Создать категорию стола',
    seating_capacity: 'Вместимость',
    meal_package: 'Пакет питания',
    rate_per_person: 'Цена на человека',
    table_category_name_placeholder: 'например, стол на 2 человек',
    photo_url_optional: 'URL фото (Необязательно)',
    description_optional: 'Описание (Необязательно)',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Создать категорию',
    failed_to_create_category: 'Не удалось создать категорию.',
    loading_table_categories: 'Загрузка категорий столов...',
    failed_to_load_table_categories: 'Не удалось загрузить категории столов.',
    all_categories: 'Все категории',
    no_table_categories_yet: 'Категорий столов пока нет.',
    capacity: 'Вместимость',
    meal: 'Питание',
    rate: 'Ставка',
    rate_dollar: 'Ставка ($)',
    saving: 'Сохранение...',
    save: 'Сохранить',
    edit: 'Редактировать',
    halls_management: 'Управление залами',
    create_hall: 'Создать зал',
    hall_name_placeholder: 'например, Главный зал',
    create_hall_button: 'Создать зал',
    failed_to_create_hall: 'Не удалось создать зал.',
    loading_halls: 'Загрузка залов...',
    failed_to_load_halls: 'Не удалось загрузить залы.',
    all_halls: 'Все залы',
    no_halls_yet: 'Залов пока нет.',
    hall_capacity: 'Вместимость',
    hall_description: 'Описание',
    hall_photo_url: 'URL фото',
    hall_active: 'Активен',
    hall_inactive: 'Неактивен'
  },
  uz: {
    banquet_admin: 'Banket Maʼmuri',
    events: 'Tadbirlar',
    menu: 'Menyu',
    tables: 'Stollar',
    halls: 'Zallar',
    tablet: 'Planshet',
    logout: 'Chiqish',
    logging_out: 'Chiqilmoqda...',
    client_menu_selection: 'Mijoz menyusi tanlovi',
    room_table_settings: 'Zal va stol sozlamalari',
    select_room: 'Zalni tanlang',
    select_table_category: 'Stol kategoriyasini tanlang',
    guests: 'Mehmonlar',
    choose_room: 'Zalni tanlang...',
    choose_table_category: 'Stol kategoriyasini tanlang...',
    selected: 'Tanlangan',
    loading_menu: 'Menyu yuklanmoqda...',
    failed_load_menu: 'Menyu yuklanmadi.',
    real_time_estimate: 'Real vaqtdagi taxmin',
    service_fee: 'Xizmat haqi',
    per_guest: 'Har bir kishi uchun',
    view_summary: 'Yakunni ko‘rish',
    selection_summary: 'Tanlov bo‘yicha yakun',
    customer_details: 'Mijoz maʼlumotlari',
    customer_name: 'Ism',
    customer_phone: 'Telefon',
    event_details: 'Tadbir maʼlumotlari',
    hall: 'Zal',
    table_category: 'Stol kategoriyasi',
    guest_count: 'Mehmonlar soni',
    selected_dishes: 'Tanlangan taomlar',
    pricing: 'Narx hisoboti',
    subtotal: 'Jami',
    tax: 'Soliq',
    total: 'Umumiy summa',
    price_per_person: 'Bir kishi uchun narx',
    summary: 'Xulosa',
    thank_you: 'Banket xizmatlarimizni tanlaganingiz uchun rahmat. Sizning tanlovingiz qayd etildi.',
    total_guests: 'Jami mehmonlar',
    estimated_total: 'Taxminiy umumiy summa',
    edit_selection: 'Tanlovni tahrirlash',
    confirm: 'Tasdiqlash',
    download_pdf: 'PDF yuklab olish',
    download_excel: 'Excel yuklab olish',
    language: 'Til',
    english: 'English',
    russian: 'Русский',
    uzbek: 'O‘zbekcha',
    banquet_events: 'Banket tadbirlari',
    create_new_event: 'Yangi tadbir yaratish',
    edit_existing_event: 'Mavjud tadbirni tahrirlash',
    phone_number: 'Telefon raqami',
    event_date_time: 'Tadbir sanasi/vaqti',
    event_type: 'Tadbir turi',
    status: 'Holat',
    hall_optional: 'Zal (Ixtiyoriy)',
    table_category_optional: 'Stol kategoriyasi (Ixtiyoriy)',
    notes: 'Izohlar',
    create_event: 'Tadbir yaratish',
    creating: 'Yaratilmoqda...',
    update_event: 'Tadbirni yangilash',
    updating: 'Yangilanmoqda...',
    cancel: 'Bekor qilish',
    loading_events: 'Tadbirlar yuklanmoqda...',
    failed_load_events: 'Tadbirlar yuklanmadi.',
    select_hall: '-- Zalni tanlang --',
    menu_management: 'Menyu boshqaruvi',
    create_menu_item: 'Menyu elementi yaratish',
    name: 'Nomi',
    description: 'Tavsif',
    category: 'Kategoriya',
    price: 'Narx',
    photo_url: 'Rasm URL',
    create: 'Yaratish',
    update: 'Yangilash',
    delete: 'O‘chirish',
    deleting: 'O‘chirilmoqda...',
    active: 'Faol',
    inactive: 'Faol emas',
    hot_appetizers: 'Issiq zakuskalar',
    first_course: 'Birinchi taom',
    second_course: 'Ikkinchi taom',
    table_categories_management: 'Stol kategoriyalari boshqaruvi',
    create_table_category: 'Stol kategoriyasini yaratish',
    seating_capacity: 'Sig‘im',
    meal_package: 'Ovqat paketi',
    rate_per_person: 'Bir kishi uchun narx',
    table_category_name_placeholder: 'masalan, 2 kishilik stol',
    photo_url_optional: 'Rasm URL (ixtiyoriy)',
    description_optional: 'Tavsif (ixtiyoriy)',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Kategoriya yaratish',
    failed_to_create_category: 'Kategoriyani yaratib bo‘lmadi.',
    loading_table_categories: 'Stol kategoriyalari yuklanmoqda...',
    failed_to_load_table_categories: 'Stol kategoriyalarini yuklab bo‘lmadi.',
    all_categories: 'Barcha kategoriyalar',
    no_table_categories_yet: 'Hali stol kategoriyalari yo‘q.',
    capacity: 'Sig‘im',
    meal: 'Ovqat',
    rate: 'Stavka',
    rate_dollar: 'Stavka ($)',
    saving: 'Saqlanmoqda...',
    save: 'Saqlash',
    edit: 'Tahrirlash',
    halls_management: 'Zallar boshqaruvi',
    create_hall: 'Zal yaratish',
    hall_name_placeholder: 'masalan, Asosiy zal',
    create_hall_button: 'Zal yaratish',
    failed_to_create_hall: 'Zalni yaratib bo‘lmadi.',
    loading_halls: 'Zallar yuklanmoqda...',
    failed_to_load_halls: 'Zallarni yuklab bo‘lmadi.',
    all_halls: 'Barcha zallar',
    no_halls_yet: 'Hali zallar yo‘q.',
    hall_capacity: 'Sig‘im',
    hall_description: 'Tavsif',
    hall_photo_url: 'Rasm URL',
    hall_active: 'Faol',
    hall_inactive: 'Faol emas'
  }
} as const;

type TranslationKey = keyof typeof resources.en;

export type { TranslationKey };

export function translate(key: TranslationKey, locale: Locale = defaultLocale, params?: Record<string, string | number>): string {
  const localeResources = (resources[locale] ?? resources[defaultLocale]) as Record<TranslationKey, string>;
  const fallbackResources = resources[defaultLocale] as Record<TranslationKey, string>;
  let value = localeResources[key] ?? fallbackResources[key] ?? key;

  if (params) {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      value = value.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue));
    });
  }

  return value;
}

export function createTranslator(locale: Locale) {
  return (key: TranslationKey, params?: Record<string, string | number>) => translate(key, locale, params);
}
