export const locales = ['en', 'ru', 'uz'];
export const defaultLocale = 'uz';
const resources = {
    en: {
        banquet_admin: 'Banquet Admin',
        events: 'Events',
        menu: 'Menu',
        tables: 'Table categories',
        halls: 'Halls',
        tablet: 'Tablet',
        logout: 'Log out',
        logging_out: 'Logging out...',
        client_menu_selection: 'Client Menu Selection',
        room_table_settings: 'Room & Table Settings',
        select_room: 'Select Room',
        select_table_category: 'Select Table Category',
        guests: 'Guests',
        choose_room: 'Choose a room...',
        choose_table_category: 'Choose a table category...',
        selected: 'Selected',
        loading_menu: 'Loading menu...',
        failed_load_menu: 'Failed to load menu.',
        real_time_estimate: 'Real-time estimate',
        per_guest: 'Per guest',
        choose_room_table_details: 'Choose your room and table settings',
        browse_menu_items: 'Browse our menu offerings and select dishes',
        price_per_guest: 'Price per guest',
        next_step: 'Next step',
        review_and_confirm: 'Review your selection before confirming',
        download_failed: 'Download failed. Please try again.',
        enter_customer_information: 'Enter customer information to confirm your order',
        overview_of_selection: 'Overview of your selected event details',
        not_selected: 'Not selected',
        selected_menu_items: 'Selected additional dishes',
        review_selected_dishes: 'Review the dishes you have chosen',
        no_items_selected: 'No items selected yet',
        actions: 'Actions',
        event_confirmed: 'Your event has been confirmed',
        view_summary: 'View Summary',
        selection_summary: 'Selection Summary',
        customer_details: 'Customer Details',
        customer_name: 'Name',
        customer_phone: 'Phone',
        event_details: 'Event Details',
        hall: 'Hall',
        table_category: 'Table Category',
        guest_count: 'Guest Count',
        selected_dishes: 'Selected Dishes',
        pricing: 'Pricing',
        subtotal: 'Subtotal',
        service_fee: 'Service Fee',
        tax: 'Tax',
        total: 'Total',
        price_per_person: 'Price per Person',
        summary: 'Summary',
        thank_you: 'Thank you for choosing our banquet services. Your selection has been recorded.',
        total_guests: 'Total guests',
        estimated_total: 'Estimated total',
        edit_selection: 'Edit Selection',
        confirm: 'Confirm',
        download_pdf: 'Download PDF',
        download_excel: 'Download Excel',
        language: 'Language',
        english: 'English',
        russian: 'Русский',
        uzbek: 'O‘zbekcha',
        banquet_events: 'Banquet Events',
        create_new_event: 'Create new event',
        edit_existing_event: 'Edit existing event',
        phone_number: 'Phone Number',
        event_date_time: 'Event date/time',
        event_type: 'Event Type',
        status: 'Status',
        hall_optional: 'Hall (Optional)',
        table_category_optional: 'Table category (Optional)',
        notes: 'Notes',
        create_event: 'Create event',
        creating: 'Creating...',
        update_event: 'Update event',
        updating: 'Updating...',
        cancel: 'Cancel',
        loading_events: 'Loading events...',
        failed_load_events: 'Failed to load events.',
        select_hall: '-- Select a hall --',
        menu_management: 'Menu Management',
        create_menu_item: 'Create Menu Item',
        name: 'Name',
        description: 'Description',
        category: 'Category',
        price: 'Price',
        photo_url: 'Photo URL',
        create: 'Create',
        update: 'Update',
        delete: 'Delete',
        deleting: 'Deleting...',
        active: 'Active',
        inactive: 'Inactive',
        cold_appetizers: 'Cold Appetizers',
        hot_appetizers: 'Hot Appetizers',
        salads: 'Salads',
        first_course: 'First Course',
        second_course: 'Second Course',
        drinks: 'Drinks',
        sweets: 'Desserts',
        fruits: 'Fruits',
        filter_all: 'All',
        food_package: 'Food Package',
        included_with_table: 'Included with your table',
        courses: 'First & Second Course',
        additional: 'Additional',
        table_categories_management: 'Table Categories Management',
        create_table_category: 'Create Table Category',
        seating_capacity: 'Seating Capacity',
        meal_package: 'Meal Package',
        rate_per_person: 'Rate per Person',
        table_category_name_placeholder: 'e.g., 2-person table',
        photo_url_optional: 'Photo URL (Optional)',
        description_optional: 'Description (Optional)',
        photo_url_placeholder: 'https://example.com/image.jpg',
        create_category: 'Create category',
        failed_to_create_category: 'Failed to create category.',
        loading_table_categories: 'Loading table categories...',
        failed_to_load_table_categories: 'Failed to load table categories.',
        all_categories: 'All Categories',
        no_table_categories_yet: 'No table categories yet.',
        capacity: 'Capacity',
        meal: 'Meal',
        rate: 'Rate',
        rate_dollar: 'Rate ($)',
        saving: 'Saving...',
        save: 'Save',
        edit: 'Edit',
        halls_management: 'Halls Management',
        create_hall: 'Create Hall',
        hall_name_placeholder: 'e.g., Main Hall',
        create_hall_button: 'Create hall',
        failed_to_create_hall: 'Failed to create hall.',
        loading_halls: 'Loading halls...',
        failed_to_load_halls: 'Failed to load halls.',
        all_halls: 'All Halls',
        no_halls_yet: 'No halls yet.',
        hall_capacity: 'Capacity',
        hall_description: 'Description',
        hall_photo_url: 'Photo URL',
        hall_active: 'Active',
        hall_inactive: 'Inactive',
        photos: 'Photos',
        photo_management: 'Photo Management',
        upload_photos: 'Upload Photos',
        photo_category: 'Photo Category',
        menu_photos: 'Menu Photos',
        hall_photos: 'Hall Photos',
        table_photos: 'Table Photos',
        dish_category: 'Dish Category',
        select_upload_files: 'Select Files',
        uploading: 'Uploading...',
        upload_photos_help: 'Upload images to manage photos for menus, halls, and tables. Max 5MB per file.',
        loading_photos: 'Loading photos...',
        failed_load_photos: 'Failed to load photos.',
        no_photos_uploaded: 'No photos uploaded yet.',
        confirm_delete_photo: 'Are you sure you want to delete this photo?',
        select_menu_photo: 'Select a photo for your menu item',
        select_hall_photo: 'Select a photo for your hall',
        select_table_photo: 'Select a photo for your table category',
        selected_photo: 'Selected',
        clear_selection: 'Clear',
        search_event_by_id: 'Search Event by ID',
        enter_event_id: 'Enter event ID',
        search: 'Search',
        search_olog_n: 'Search',
        event_not_found: 'Event with ID {id} not found',
        search_result: 'Search Result',
        no_events_loaded: 'No events loaded',
        start_new_booking: 'Start New Booking',
        submitting: 'Submitting...',
        event_create_error: 'Failed to create event. Please try again.',
        notes_placeholder: 'Any special requests or comments...',
        event_date: 'Event Date',
        event_time: 'Event Time',
        select_restaurant: 'Select a restaurant',
        my_restaurants: 'My Restaurants',
        restaurants_management: 'My Restaurants',
        create_restaurant: 'Create Restaurant',
        restaurant_name: 'Restaurant Name',
        restaurant_address: 'Address',
        restaurant_logo_url: 'Logo URL',
        restaurant_name_placeholder: 'e.g., Madinabek Banquet',
        restaurant_address_placeholder: 'e.g., 12 Main Street, Tashkent',
        no_restaurants_yet: 'No restaurants yet. Create one to get started.',
        loading_restaurants: 'Loading restaurants...',
        failed_load_restaurants: 'Failed to load restaurants.',
        confirm_delete_restaurant: 'Are you sure you want to delete this restaurant?',
        users: 'Users',
        users_management: 'Users Management',
        create_user: 'Create User',
        user_role: 'Role',
        role_owner: 'Owner',
        role_admin: 'Administrator',
        role_employee: 'Employee',
        confirm_delete_user: 'Are you sure you want to delete this user?',
        no_users_yet: 'No users yet.',
        loading_users: 'Loading users...',
        failed_load_users: 'Failed to load users.',
        change_role: 'Change Role',
        password: 'Password',
        event_type_reservation: 'Reservation',
        event_type_banquet: 'Banquet',
        event_type_wedding: 'Wedding',
        event_type_birthday: 'Birthday',
        event_type_private_party: 'Private Party',
        event_type_corporate: 'Corporate',
        birthday_person_name: "Birthday Person's Name",
        birthday_person_name_placeholder: 'First and last name',
        bride_name: "Bride's Name",
        groom_name: "Groom's Name",
        bride_groom_name_placeholder: 'First and last name',
        honoree_person_name: "Name",
        honoree_person_name_placeholder: 'First and last name'
    },
    ru: {
        banquet_admin: 'Админ Банкет',
        events: 'События',
        menu: 'Меню',
        tables: 'Категории столов',
        halls: 'Залы',
        tablet: 'Планшет',
        logout: 'Выйти',
        logging_out: 'Выход...',
        client_menu_selection: 'Выбор меню клиента',
        room_table_settings: 'Нastройки зала и столов',
        select_room: 'Выбрать зал',
        select_table_category: 'Выбрать категорию стола',
        guests: 'Гостей',
        choose_room: 'Выберите зал...',
        choose_table_category: 'Выберите категорию стола...',
        selected: 'Выбрано',
        loading_menu: 'Загрузка меню...',
        failed_load_menu: 'Не удалось загрузить меню.',
        real_time_estimate: 'Оценка в реальном времени',
        per_guest: 'На гостя',
        choose_room_table_details: 'Выберите настройки зала и стола',
        browse_menu_items: 'Просмотрите меню и выберите блюда',
        price_per_guest: 'Цена за гостя',
        next_step: 'Следующий шаг',
        review_and_confirm: 'Проверьте выбор перед подтверждением',
        download_failed: 'Не удалось скачать. Пожалуйста, попробуйте снова.',
        enter_customer_information: 'Введите данные клиента для подтверждения заказа',
        overview_of_selection: 'Обзор выбранных данных мероприятия',
        not_selected: 'Не выбрано',
        selected_menu_items: 'Выбранные дополнительные блюда',
        review_selected_dishes: 'Проверьте выбранные блюда',
        no_items_selected: 'Пока нет выбранных пунктов',
        actions: 'Действия',
        event_confirmed: 'Ваше событие подтверждено',
        view_summary: 'Просмотреть итоги',
        selection_summary: 'Итоговый выбор',
        customer_details: 'Данные клиента',
        customer_name: 'Имя',
        customer_phone: 'Телефон',
        event_details: 'Данные мероприятия',
        hall: 'Зал',
        table_category: 'Категория стола',
        guest_count: 'Количество гостей',
        selected_dishes: 'Выбранные блюда',
        pricing: 'Ценообразование',
        subtotal: 'Промежуточный итог',
        tax: 'Налог',
        total: 'Итого',
        price_per_person: 'Цена на человека',
        summary: 'Итог',
        thank_you: 'Спасибо за выбор наших банкетных услуг. Ваш выбор был зафиксирован.',
        total_guests: 'Всего гостей',
        estimated_total: 'Ориентировочная сумма',
        edit_selection: 'Редактировать выбор',
        confirm: 'Подтвердить',
        download_pdf: 'Скачать PDF',
        download_excel: 'Скачать Excel',
        language: 'Язык',
        english: 'English',
        russian: 'Русский',
        uzbek: 'O‘zbekcha',
        banquet_events: 'Банкетные события',
        create_new_event: 'Создать новое событие',
        edit_existing_event: 'Редактировать существующее событие',
        phone_number: 'Номер телефона',
        event_date_time: 'Дата/время события',
        event_type: 'Тип события',
        status: 'Статус',
        hall_optional: 'Зал (Необязательно)',
        table_category_optional: 'Категория стола (Необязательно)',
        notes: 'Заметки',
        create_event: 'Создать событие',
        creating: 'Создание...',
        update_event: 'Обновить событие',
        updating: 'Обновление...',
        cancel: 'Отмена',
        loading_events: 'Загрузка событий...',
        failed_load_events: 'Не удалось загрузить события.',
        select_hall: '-- Выберите зал --',
        menu_management: 'Управление меню',
        create_menu_item: 'Создать пункт меню',
        name: 'Название',
        description: 'Описание',
        category: 'Категория',
        price: 'Цена',
        photo_url: 'URL фото',
        create: 'Создать',
        update: 'Обновить',
        delete: 'Удалить',
        deleting: 'Удаление...',
        active: 'Активен',
        inactive: 'Неактивен',
        cold_appetizers: 'Холодные закуски',
        hot_appetizers: 'Горячие закуски',
        salads: 'Салаты',
        first_course: 'Первое блюдо',
        second_course: 'Второе блюдо',
        drinks: 'Напитки',
        sweets: 'Десерты',
        fruits: 'Фрукты',
        filter_all: 'Все',
        food_package: 'Пакет питания',
        included_with_table: 'Включено в ваш стол',
        courses: 'Первое и второе блюдо',
        additional: 'Дополнительно',
        table_categories_management: 'Управление категориями столов',
        create_table_category: 'Создать категорию стола',
        seating_capacity: 'Вместимость',
        meal_package: 'Пакет питания',
        rate_per_person: 'Цена на человека',
        table_category_name_placeholder: 'например, стол на 2 человек',
        photo_url_optional: 'URL фото (Необязательно)',
        description_optional: 'Описание (Необязательно)',
        photo_url_placeholder: 'https://example.com/image.jpg',
        create_category: 'Создать категорию',
        failed_to_create_category: 'Не удалось создать категорию.',
        loading_table_categories: 'Загрузка категорий столов...',
        failed_to_load_table_categories: 'Не удалось загрузить категории столов.',
        all_categories: 'Все категории',
        no_table_categories_yet: 'Категорий столов пока нет.',
        capacity: 'Вместимость',
        meal: 'Питание',
        rate: 'Ставка',
        rate_dollar: 'Ставка ($)',
        saving: 'Сохранение...',
        save: 'Сохранить',
        edit: 'Редактировать',
        halls_management: 'Управление залами',
        create_hall: 'Создать зал',
        hall_name_placeholder: 'например, Главный зал',
        create_hall_button: 'Создать зал',
        failed_to_create_hall: 'Не удалось создать зал.',
        loading_halls: 'Загрузка залов...',
        failed_to_load_halls: 'Не удалось загрузить залы.',
        all_halls: 'Все залы',
        no_halls_yet: 'Залов пока нет.',
        hall_capacity: 'Вместимость',
        hall_description: 'Описание',
        hall_photo_url: 'URL фото',
        hall_active: 'Активен',
        hall_inactive: 'Неактивен',
        photos: 'Фотографии',
        photo_management: 'Управление фотографиями',
        upload_photos: 'Загрузить фотографии',
        photo_category: 'Категория фотографий',
        menu_photos: 'Фотографии меню',
        hall_photos: 'Фотографии залов',
        table_photos: 'Фотографии столов',
        dish_category: 'Категория блюда',
        select_upload_files: 'Выбрать файлы',
        uploading: 'Загрузка...',
        upload_photos_help: 'Загружайте изображения для управления фотографиями меню, залов и столов. Макс 5 МБ на файл.',
        loading_photos: 'Загрузка фотографий...',
        failed_load_photos: 'Не удалось загрузить фотографии.',
        no_photos_uploaded: 'Фотографии еще не загружены.',
        confirm_delete_photo: 'Вы уверены, что хотите удалить эту фотографию?',
        select_menu_photo: 'Выберите фотографию для пункта меню',
        select_hall_photo: 'Выберите фотографию для зала',
        select_table_photo: 'Выберите фотографию для категории стола',
        selected_photo: 'Выбрано',
        clear_selection: 'Очистить',
        search_event_by_id: 'Поиск события по ID',
        enter_event_id: 'Введите ID события',
        search: 'Поиск',
        search_olog_n: 'Поиск',
        event_not_found: 'Событие с ID {id} не найдено',
        search_result: 'Результат поиска',
        no_events_loaded: 'События не загружены',
        start_new_booking: 'Новое бронирование',
        submitting: 'Отправка...',
        event_create_error: 'Не удалось создать событие. Попробуйте ещё раз.',
        notes_placeholder: 'Особые пожелания или комментарии...',
        event_date: 'Дата события',
        event_time: 'Время события',
        select_restaurant: 'Выберите ресторан',
        my_restaurants: 'Мои рестораны',
        restaurants_management: 'Мои рестораны',
        create_restaurant: 'Создать ресторан',
        restaurant_name: 'Название ресторана',
        restaurant_address: 'Адрес',
        restaurant_logo_url: 'URL логотипа',
        restaurant_name_placeholder: 'например, Банкет Мадинабек',
        restaurant_address_placeholder: 'например, ул. Главная 12, Ташкент',
        no_restaurants_yet: 'Ресторанов пока нет. Создайте первый.',
        loading_restaurants: 'Загрузка ресторанов...',
        failed_load_restaurants: 'Не удалось загрузить рестораны.',
        confirm_delete_restaurant: 'Вы уверены, что хотите удалить этот ресторан?',
        users: 'Пользователи',
        users_management: 'Управление пользователями',
        create_user: 'Создать пользователя',
        user_role: 'Роль',
        role_owner: 'Владелец',
        role_admin: 'Администратор',
        role_employee: 'Сотрудник',
        confirm_delete_user: 'Вы уверены, что хотите удалить этого пользователя?',
        no_users_yet: 'Пользователей пока нет.',
        loading_users: 'Загрузка пользователей...',
        failed_load_users: 'Не удалось загрузить пользователей.',
        change_role: 'Изменить роль',
        password: 'Пароль',
        event_type_reservation: 'Бронирование',
        event_type_banquet: 'Банкет',
        event_type_wedding: 'Свадьба',
        event_type_birthday: 'День рождения',
        event_type_private_party: 'Частная вечеринка',
        event_type_corporate: 'Корпоратив',
        birthday_person_name: 'Имя именинника',
        birthday_person_name_placeholder: 'Имя и фамилия',
        bride_name: 'Имя невесты',
        groom_name: 'Имя жениха',
        bride_groom_name_placeholder: 'Имя и фамилия',
        honoree_person_name: 'Имя',
        honoree_person_name_placeholder: 'Имя и фамилия'
    },
    uz: {
        banquet_admin: 'Banket Maʼmuri',
        events: 'Tadbirlar',
        menu: 'Menyu',
        tables: 'Jadval Toifalari',
        halls: 'Zallar',
        tablet: 'Planshet',
        logout: 'Chiqish',
        logging_out: 'Chiqilmoqda...',
        client_menu_selection: 'Mijoz menyusi tanlovi',
        room_table_settings: 'Zal va stol sozlamalari',
        select_room: 'Zalni tanlang',
        select_table_category: 'Stol kategoriyasini tanlang',
        guests: 'Mehmonlar',
        choose_room: 'Zalni tanlang...',
        choose_table_category: 'Stol kategoriyasini tanlang...',
        selected: 'Tanlangan',
        loading_menu: 'Menyu yuklanmoqda...',
        failed_load_menu: 'Menyu yuklanmadi.',
        real_time_estimate: 'Real vaqtdagi taxmin',
        per_guest: 'Har bir kishi uchun',
        choose_room_table_details: 'Zal va stol sozlamalarini tanlang',
        browse_menu_items: 'Menyu bo‘limlarini ko‘rib chiqing va taomlarni tanlang',
        price_per_guest: 'Bir mehmon uchun narx',
        next_step: 'Keyingi qadam',
        review_and_confirm: 'Tanlovni tasdiqlashdan oldin tekshiring',
        download_failed: 'Yuklab olish muvaffaqiyatsiz tugadi. Iltimos, qayta urinib ko‘ring.',
        enter_customer_information: 'Buyurtmani tasdiqlash uchun mijoz maʼlumotlarini kiriting',
        overview_of_selection: 'Tanlangan tadbir tafsilotlari bo‘yicha umumiy maʼlumot',
        not_selected: 'Tanlanmagan',
        selected_menu_items: 'Tanlangan qo‘shimcha taomlar',
        review_selected_dishes: 'Tanlangan taomlarni tekshiring',
        no_items_selected: 'Hali hech qanday element tanlanmagan',
        actions: 'Harakatlar',
        event_confirmed: 'Sizning tadbiringiz tasdiqlandi',
        view_summary: 'Yakunni ko‘rish',
        selection_summary: 'Tanlov bo‘yicha yakun',
        customer_details: 'Mijoz maʼlumotlari',
        customer_name: 'Ism',
        customer_phone: 'Telefon',
        event_details: 'Tadbir maʼlumotlari',
        hall: 'Zal',
        table_category: 'Stol kategoriyasi',
        guest_count: 'Mehmonlar soni',
        selected_dishes: 'Tanlangan taomlar',
        pricing: 'Narx hisoboti',
        subtotal: 'Jami',
        tax: 'Soliq',
        total: 'Umumiy summa',
        price_per_person: 'Bir kishi uchun narx',
        summary: 'Xulosa',
        thank_you: 'Banket xizmatlarimizni tanlaganingiz uchun rahmat. Sizning tanlovingiz qayd etildi.',
        total_guests: 'Jami mehmonlar',
        estimated_total: 'Taxminiy umumiy summa',
        edit_selection: 'Tanlovni tahrirlash',
        confirm: 'Tasdiqlash',
        download_pdf: 'PDF yuklab olish',
        download_excel: 'Excel yuklab olish',
        language: 'Til',
        english: 'English',
        russian: 'Русский',
        uzbek: 'O‘zbekcha',
        banquet_events: 'Banket tadbirlari',
        create_new_event: 'Yangi tadbir yaratish',
        edit_existing_event: 'Mavjud tadbirni tahrirlash',
        phone_number: 'Telefon raqami',
        event_date_time: 'Tadbir sanasi/vaqti',
        event_type: 'Tadbir turi',
        status: 'Holat',
        hall_optional: 'Zal (Ixtiyoriy)',
        table_category_optional: 'Stol kategoriyasi (Ixtiyoriy)',
        notes: 'Izohlar',
        create_event: 'Tadbir yaratish',
        creating: 'Yaratilmoqda...',
        update_event: 'Tadbirni yangilash',
        updating: 'Yangilanmoqda...',
        cancel: 'Bekor qilish',
        loading_events: 'Tadbirlar yuklanmoqda...',
        failed_load_events: 'Tadbirlar yuklanmadi.',
        select_hall: '-- Zalni tanlang --',
        menu_management: 'Menyu boshqaruvi',
        create_menu_item: 'Menyu elementi yaratish',
        name: 'Nomi',
        description: 'Tavsif',
        category: 'Kategoriya',
        price: 'Narx',
        photo_url: 'Rasm URL',
        create: 'Yaratish',
        update: 'Yangilash',
        delete: 'O‘chirish',
        deleting: 'O‘chirilmoqda...',
        active: 'Faol',
        inactive: 'Faol emas',
        cold_appetizers: 'Sovuq zakuskalar',
        hot_appetizers: 'Issiq zakuskalar',
        salads: 'Salatlar',
        first_course: 'Birinchi taom',
        second_course: 'Ikkinchi taom',
        drinks: 'Ichimliklar',
        sweets: 'Desertlar',
        fruits: 'Mevalar',
        filter_all: 'Hammasi',
        food_package: 'Ovqat paketi',
        included_with_table: 'Stolingizga kiritilgan',
        courses: 'Birinchi va ikkinchi taom',
        additional: 'Qo\'shimcha',
        table_categories_management: 'Stol kategoriyalari boshqaruvi',
        create_table_category: 'Stol kategoriyasini yaratish',
        seating_capacity: 'Sig‘im',
        meal_package: 'Ovqat paketi',
        rate_per_person: 'Bir kishi uchun narx',
        table_category_name_placeholder: 'masalan, 2 kishilik stol',
        photo_url_optional: 'Rasm URL (ixtiyoriy)',
        description_optional: 'Tavsif (ixtiyoriy)',
        photo_url_placeholder: 'https://example.com/image.jpg',
        create_category: 'Kategoriya yaratish',
        failed_to_create_category: 'Kategoriyani yaratib bo‘lmadi.',
        loading_table_categories: 'Stol kategoriyalari yuklanmoqda...',
        failed_to_load_table_categories: 'Stol kategoriyalarini yuklab bo‘lmadi.',
        all_categories: 'Barcha kategoriyalar',
        no_table_categories_yet: 'Hali stol kategoriyalari yo‘q.',
        capacity: 'Sig‘im',
        meal: 'Ovqat',
        rate: 'Stavka',
        rate_dollar: 'Stavka ($)',
        saving: 'Saqlanmoqda...',
        save: 'Saqlash',
        edit: 'Tahrirlash',
        halls_management: 'Zallar boshqaruvi',
        create_hall: 'Zal yaratish',
        hall_name_placeholder: 'masalan, Asosiy zal',
        create_hall_button: 'Zal yaratish',
        failed_to_create_hall: 'Zalni yaratib bo‘lmadi.',
        loading_halls: 'Zallar yuklanmoqda...',
        failed_to_load_halls: 'Zallarni yuklab bo‘lmadi.',
        all_halls: 'Barcha zallar',
        no_halls_yet: 'Hali zallar yo‘q.',
        hall_capacity: 'Sig‘im',
        hall_description: 'Tavsif',
        hall_photo_url: 'Rasm URL',
        hall_active: 'Faol',
        hall_inactive: 'Faol emas',
        photos: 'Rasmlar',
        photo_management: 'Rasmlarni boshqarish',
        upload_photos: 'Rasmlarni yuklash',
        photo_category: 'Rasmlar kategoriyasi',
        menu_photos: 'Menyu rasmlari',
        hall_photos: 'Zal rasmlari',
        table_photos: 'Stol rasmlari',
        dish_category: 'Taom kategoriyasi',
        select_upload_files: 'Fayllarni tanlang',
        uploading: 'Yuklanmoqda...',
        upload_photos_help: 'Menyu, zallar va stollar uchun rasmlarni boshqarish uchun rasmlarni yükleyin. Maksimal 5 MB har bir fayl.',
        loading_photos: 'Rasmlar yuklanmoqda...',
        failed_load_photos: 'Rasmlarni yuklab bolmadi.',
        no_photos_uploaded: 'Hali rasmlar yuklenmagan.',
        confirm_delete_photo: 'Siz bu rasmni ochirib tashlamoqchimisiz?',
        select_menu_photo: 'Menyu elementi uchun rasm tanlang',
        select_hall_photo: 'Zal uchun rasm tanlang',
        select_table_photo: 'Stol kategoriyasi uchun rasm tanlang',
        selected_photo: 'Tanlangan',
        clear_selection: 'Tozalash',
        search_event_by_id: 'ID bo\'yicha tadbir qidirish',
        enter_event_id: 'Tadbir ID sini kiriting',
        search: 'Qidirish',
        search_olog_n: 'Qidirish',
        event_not_found: '{id} ID li tadbir topilmadi',
        search_result: 'Qidiruv natijasi',
        no_events_loaded: 'Tadbirlar yuklanmagan',
        start_new_booking: 'Yangi bron',
        submitting: 'Yuborilmoqda...',
        event_create_error: 'Tadbir yaratib bo\'lmadi. Qayta urinib ko\'ring.',
        notes_placeholder: 'Maxsus so\'rovlar yoki izohlar...',
        event_date: 'Tadbir sanasi',
        event_time: 'Tadbir vaqti',
        select_restaurant: 'Restoran tanlang',
        my_restaurants: 'Mening restoranlarim',
        restaurants_management: 'Mening restoranlarim',
        create_restaurant: 'Restoran yaratish',
        restaurant_name: 'Restoran nomi',
        restaurant_address: 'Manzil',
        restaurant_logo_url: 'Logo URL',
        restaurant_name_placeholder: 'masalan, Madinabek Banket',
        restaurant_address_placeholder: 'masalan, Asosiy ko\'cha 12, Toshkent',
        no_restaurants_yet: 'Hali restoranlar yo\'q. Birinchisini yarating.',
        loading_restaurants: 'Restoranlar yuklanmoqda...',
        failed_load_restaurants: 'Restoranlarni yuklab bo\'lmadi.',
        confirm_delete_restaurant: 'Siz bu restoranni o\'chirmoqchimisiz?',
        users: 'Foydalanuvchilar',
        users_management: 'Foydalanuvchilarni boshqarish',
        create_user: 'Foydalanuvchi yaratish',
        user_role: 'Rol',
        role_owner: 'Egasi',
        role_admin: 'Administrator',
        role_employee: 'Xodim',
        confirm_delete_user: 'Siz bu foydalanuvchini o\'chirmoqchimisiz?',
        no_users_yet: 'Hali foydalanuvchilar yo\'q.',
        loading_users: 'Foydalanuvchilar yuklanmoqda...',
        failed_load_users: 'Foydalanuvchilarni yuklab bo\'lmadi.',
        change_role: 'Rolni o\'zgartirish',
        password: 'Parol',
        event_type_reservation: 'Bron',
        event_type_banquet: 'Banket',
        event_type_wedding: 'To\'y',
        event_type_birthday: 'Tug\'ilgan kun',
        event_type_private_party: 'Xususiy ziyofat',
        event_type_corporate: 'Korporativ',
        birthday_person_name: 'Tug\'ilgan kun egasining ismi',
        birthday_person_name_placeholder: 'Ism va familiya',
        bride_name: 'Kelinchak ismi',
        groom_name: 'Kuyov ismi',
        bride_groom_name_placeholder: 'Ism va familiya',
        honoree_person_name: 'Ism',
        honoree_person_name_placeholder: 'Ism va familiya'
    }
};
export function translate(key, locale = defaultLocale, params) {
    const localeResources = (resources[locale] ?? resources[defaultLocale]);
    const fallbackResources = resources[defaultLocale];
    let value = localeResources[key] ?? fallbackResources[key] ?? key;
    if (params) {
        Object.entries(params).forEach(([paramKey, paramValue]) => {
            value = value.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue));
        });
    }
    return value;
}
export function createTranslator(locale) {
    return (key, params) => translate(key, locale, params);
}
