export type Locale = 'en' | 'ru' | 'uz';

export const locales: Locale[] = ['en', 'ru', 'uz'];

export const defaultLocale: Locale = 'uz';

const resources = {
  en: {
    banquet_admin: 'Banquet Admin',
    events: 'Events',
    menu: 'Menu',
    tables: 'Table categories',
    halls: 'Halls',
    tablet: 'Tablet',
    logout: 'Log out',
    logging_out: 'Logging out...',
    client_menu_selection: 'Client Menu Selection',
    room_table_settings: 'Room & Table Settings',
    select_room: 'Select Room',
    select_table_category: 'Select Table Category',
    free_for_this_table: 'Free for this table',
    no_table_categories: 'No table categories yet — create one first',
    guests: 'Guests',
    choose_room: 'Choose a room...',
    choose_table_category: 'Choose a table category...',
    selected: 'Selected',
    loading_menu: 'Loading menu...',
    failed_load_menu: 'Failed to load menu.',
    real_time_estimate: 'Real-time estimate',
    per_guest: 'Per guest',
    choose_room_table_details: 'Choose your room and table settings',
    browse_menu_items: 'Browse our menu offerings and select dishes',
    price_per_guest: 'Price per guest',
    next_step: 'Next step',
    review_and_confirm: 'Review your selection before confirming',
    download_failed: 'Download failed. Please try again.',
    enter_customer_information: 'Enter customer information to confirm your order',
    overview_of_selection: 'Overview of your selected event details',
    not_selected: 'Not selected',
    selected_menu_items: 'Selected additional dishes',
    review_selected_dishes: 'Review the dishes you have chosen',
    no_items_selected: 'No items selected yet',
    actions: 'Actions',
    event_confirmed: 'Your event has been confirmed',
    view_summary: 'View Summary',
    change_menu: 'Change Menu',
    create_menu: 'Create Menu',
    second_customer_name: 'Second Person Name (optional)',
    second_customer_phone: 'Second Person Phone (optional)',
    deposit: 'Deposit',
    deposit_optional: 'Deposit (optional)',
    amount_due: 'Amount Due',
    general: 'General',
    reschedule: 'Reschedule',
    reschedule_event: 'Reschedule Event',
    new_date: 'New Date',
    new_time: 'New Time',
    rescheduled_from: 'Rescheduled from',
    create_new_event_button: 'Create New Event',
    hide_form: 'Hide',
    change_first_course: 'Change first course',
    change_second_course: 'Change second course',
    change_third_course: 'Change third course',
    collapse_options: 'Collapse',
    included_dishes: 'Included dishes',
    differences_highlighted: 'Differences highlighted',
    customer_information: 'Customer Information',
    notifications: 'Notifications',
    no_notifications: 'No notifications',
    overdue_debts_subtitle: 'Unpaid debts past their settlement deadline',
    debt: 'Debt',
    debt_overdue: 'Debt overdue',
    debt_overdue_notice: 'Outstanding debt: {amount}',
    debt_deadline: 'Debt settlement deadline',
    payment: 'Payment',
    payment_amount: 'Payment amount',
    add_payment: 'Add payment',
    edit_menu: 'Edit Menu',
    selection_summary: 'Selection Summary',
    menu_for_banquet: 'MENU FOR BANQUET',
    dish_name: 'Dish name',
    qty_pcs: 'Qty (pcs)',
    date: 'Date',
    customer_details: 'Customer Details',
    customer_name: 'Name',
    customer_phone: 'Phone',
    event_details: 'Event Details',
    hall: 'Hall',
    table_category: 'Table Category',
    guest_count: 'Guest Count',
    selected_dishes: 'Selected Dishes',
    additional_dishes: 'Additional Dishes',
    table_category_dishes: 'Table category dishes',
    pricing: 'Pricing',
    subtotal: 'Subtotal',
    service_fee: 'Service Fee',
    tax: 'Tax',
    total: 'Total',
    price_per_person: 'Price per Person',
    summary: 'Summary',
    thank_you: 'Thank you for choosing our banquet services. Your selection has been recorded.',
    total_guests: 'Total guests',
    estimated_total: 'Estimated total',
    edit_selection: 'Edit Selection',
    confirm: 'Confirm',
    download_pdf: 'Download PDF',
    download_excel: 'Download Excel',
    language: 'Language',
    english: 'English',
    translations: 'Translations',
    translations_hint: 'Optional — shown on the tablet and catering site per language. Falls back to the main text.',
    russian: 'Русский',
    uzbek: 'O\'zbekcha',
    banquet_events: 'Banquet Events',
    create_new_event: 'Create new event',
    edit_existing_event: 'Edit existing event',
    phone_number: 'Phone Number',
    event_date_time: 'Event date/time',
    event_type: 'Event Type',
    status: 'Status',
    hall_optional: 'Hall (Optional)',
    table_category_optional: 'Table category (Optional)',
    notes: 'Notes',
    create_event: 'Create event',
    creating: 'Creating...',
    update_event: 'Update event',
    updating: 'Updating...',
    cancel: 'Cancel',
    loading_events: 'Loading events...',
    failed_load_events: 'Failed to load events.',
    invoices: 'Invoices',
    invoice_one: 'invoice',
    invoice_many: 'invoices',
    invoices_open: 'Open',
    invoices_outstanding: 'Outstanding',
    invoices_paid: 'Paid',
    billable_total: 'Billable total',
    table_package: 'Table package',
    round_up_to_million: 'Round down to nearest million',
    rounded_to_million: 'Rounded down to the nearest million',
    close_invoice: 'Close Invoice',
    closing: 'Closing…',
    invoice_closed: 'Closed',
    no_invoices: 'No events to invoice yet.',
    status_draft: 'Draft',
    status_confirmed: 'Confirmed',
    status_cancelled: 'Cancelled',
    status_completed: 'Completed',
    status_menu_not_selected: 'Menu not selected',
    ev_col_customer: 'Customer',
    ev_col_datetime: 'Date / Time',
    ev_col_hall_table: 'Hall / Table',
    no_events_yet: 'No events yet.',
    dishes_count: '{count} dishes',
    dish_count_one: '1 dish',
    pcs_total: '{count} pcs total',
    hidden_label: 'Hidden',
    do_not_show: 'Do not show',
    show_subcategory: 'Show',
    disable_subcategories: 'Disable subcategories',
    disable_subcategories_help: 'Master switch — when on, subcategories are turned off everywhere: the menu items Subcategory column is hidden and the catering site shows no subcategory headers, regardless of the individual subcategories below.',
    subcategories_enabled: 'Subcategories on',
    subcategories_disabled: 'Subcategories off',
    more: 'More',
    settings: 'Settings',
    excluded_categories: 'Excluded dish categories',
    excluded_categories_help: 'Checked categories are unavailable and hidden everywhere — menus, table categories, and photos. Their existing dishes stay saved and reappear if you uncheck the category.',
    excluded_count: '{count} category excluded',
    nothing_excluded: 'No categories excluded — everything is available.',
    save_settings: 'Save settings',
    settings_saved: 'Settings saved.',
    settings_save_failed: 'Failed to save settings.',
    select_hall: '-- Select a hall --',
    menu_management: 'Menu Management',
    create_menu_item: 'Create Menu Item',
    name: 'Name',
    name_optional: 'Name (optional)',
    blank_uses_company_name: 'Leave blank to use the company name.',
    description: 'Description',
    category: 'Category',
    price: 'Price',
    photo_url: 'Photo URL',
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    deleting: 'Deleting...',
    active: 'Active',
    inactive: 'Inactive',
    cold_appetizers: 'Cold Appetizers',
    hot_appetizers: 'Hot Appetizers',
    your_selection: 'Your selection',
    assorted: 'Assorted',
    salads: 'Salads',
    first_course: 'First Course',
    second_course: 'Second Course',
    third_course: 'Third Course',
    drinks: 'Drinks',
    sweets: 'Desserts',
    fruits: 'Fruits',
    soups: 'Soups',
    pizza: 'Pizza',
    grill: 'Grill',
    pastry: 'Pastry',
    beer_snacks: 'Beer Snacks',
    dessert: 'Dessert',
    lamb_dishes: 'Lamb Dishes',
    beef_dishes: 'Beef Dishes',
    chicken_dishes: 'Chicken Dishes',
    side_dishes: 'Side Dishes',
    pasta: 'Pasta',
    soft_drinks: 'Soft Drinks',
    steaks: 'Steaks',
    energy_drinks: 'Energy Drinks',
    salads_oil: 'Oil-Based Salads',
    salads_mayo: 'Mayonnaise-Based Salads',
    coffee: 'Coffee',
    sushi_rolls: 'Sushi and Rolls',
    dried_fruits: 'Dried Fruits',
    candies: 'Candies',
    alcohol: 'Alcohol',
    lemonades: 'Lemonades',
    non_alcoholic_cocktails: 'Non-Alcoholic Cocktails',
    alcoholic_cocktails: 'Alcoholic Cocktails',
    milkshakes: 'Milkshakes',
    tea_menu: 'Tea Card',
    fresh_juices: 'Freshly Squeezed Juices',
    liqueurs: 'Liqueurs',
    filter_all: 'All',
    food_package: 'Food Package',
    included_with_table: 'Included with your table',
    servings_per_table: 'Servings per table',
    courses: 'First & Second Course',
    additional: 'Additional',
    additional_management: 'Additional Dishes',
    additional_help: 'Set each dish\'s status: "Paid" shows it as a paid additional item on the tablet, "Free" lets guests use it as a free replacement for included dishes, and "Don\'t show" hides it from both.',
    status_dont_show: 'Don\'t show',
    status_free: 'Free',
    status_paid: 'Paid',
    swap_free: 'Swap for free',
    choose_replacement: 'Choose a replacement',
    included_default: 'included',
    revert_to_default: 'Revert to included dish',
    table_type: 'Table type',
    table_type_adult: 'Adult table',
    table_type_children: "Children's table",
    children_table: "Children's table",
    add_children_table: "Add children's table",
    children_table_included: "Children's table added",
    children_count: 'Number of children',
    subcategories: 'Subcategories',
    subcategory: 'Subcategory',
    subcategories_help: 'Create subcategories to divide each dish category into sections on the catering site.',
    create_subcategory: 'Create subcategory',
    subcategory_name: 'Subcategory name',
    add_subcategory: 'Add subcategory',
    no_subcategories_yet: 'No subcategories yet.',
    no_subcategory: 'No subcategory',
    delete_subcategory_confirm: 'Delete this subcategory?',
    other: 'Other',
    show_on_tablet: 'Shown on tablet',
    bestseller: 'Bestseller',
    bestsellers_only: 'Bestsellers only',
    out_of_stock: 'Out of stock',
    attach_photo: 'Attach photo',
    shown: 'Shown',
    hidden: 'Hidden',
    discount: 'Discount',
    discount_percent: 'Discount (%)',
    apply_discount: 'Apply discount',
    original_price: 'Original price',
    discounted_price: 'Discounted price',
    no_additional_dishes: 'No additional dishes yet. Add them on the Menu page.',
    table_categories_management: 'Table Categories Management',
    create_table_category: 'Create Table Category',
    seating_capacity: 'Seating Capacity',
    meal_package: 'Meal Package',
    rate_per_person: 'Rate per Person',
    table_category_name_placeholder: 'e.g., 2-person table',
    photo_url_optional: 'Photo URL (Optional)',
    description_optional: 'Description (Optional)',
    required: 'Required',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Create category',
    failed_to_create_category: 'Failed to create category.',
    loading_table_categories: 'Loading table categories...',
    failed_to_load_table_categories: 'Failed to load table categories.',
    all_categories: 'All Categories',
    no_table_categories_yet: 'No table categories yet.',
    capacity: 'Capacity',
    meal: 'Meal',
    rate: 'Rate',
    rate_dollar: 'Rate ($)',
    saving: 'Saving...',
    save: 'Save',
    edit: 'Edit',
    halls_management: 'Halls Management',
    create_hall: 'Create Hall',
    hall_name_placeholder: 'e.g., Main Hall',
    create_hall_button: 'Create hall',
    failed_to_create_hall: 'Failed to create hall.',
    loading_halls: 'Loading halls...',
    failed_to_load_halls: 'Failed to load halls.',
    all_halls: 'All Halls',
    no_halls_yet: 'No halls yet.',
    hall_capacity: 'Capacity',
    hall_description: 'Description',
    hall_photo_url: 'Photo URL',
    hall_active: 'Active',
    hall_inactive: 'Inactive',
    photos: 'Photos',
    photo_management: 'Photo Management',
    upload_photos: 'Upload Photos',
    photo_category: 'Photo Category',
    menu_photos: 'Menu Photos',
    hall_photos: 'Hall Photos',
    table_photos: 'Table Photos',
    table_categories: 'Table Categories',
    select_table: 'Select this table',
    person: 'person',
    dish_category: 'Dish Category',
    select_upload_files: 'Select Files',
    uploading: 'Uploading...',
    upload_photos_help: 'Upload images to manage photos for menus, halls, and tables. Max 5MB per file.',
    loading_photos: 'Loading photos...',
    failed_load_photos: 'Failed to load photos.',
    no_photos_uploaded: 'No photos uploaded yet.',
    confirm_delete_photo: 'Are you sure you want to delete this photo?',
    select_menu_photo: 'Select a photo for your menu item',
    select_hall_photo: 'Select a photo for your hall',
    select_table_photo: 'Select a photo for your table category',
    selected_photo: 'Selected',
    clear_selection: 'Clear',
    search_event_by_id: 'Search Event by ID',
    enter_event_id: 'Enter event ID',
    search: 'Search',
    search_olog_n: 'Search',
    event_not_found: 'Event with ID {id} not found',
    search_result: 'Search Result',
    no_events_loaded: 'No events loaded',
    start_new_booking: 'Start New Booking',
    submitting: 'Submitting...',
    event_create_error: 'Failed to create event. Please try again.',
    notes_placeholder: 'Any special requests or comments...',
    event_date: 'Event Date',
    event_time: 'Event Time',
    select_restaurant: 'Select a restaurant',
    my_restaurants: 'My Restaurants',
    restaurants_management: 'My Restaurants',
    create_restaurant: 'Create Restaurant',
    restaurant_name: 'Restaurant Name',
    restaurant_address: 'Address',
    restaurant_logo_url: 'Logo URL',
    restaurant_name_placeholder: 'e.g., Madinabek Banquet',
    restaurant_address_placeholder: 'e.g., 12 Main Street, Tashkent',
    no_restaurants_yet: 'No restaurants yet. Create one to get started.',
    loading_restaurants: 'Loading restaurants...',
    failed_load_restaurants: 'Failed to load restaurants.',
    confirm_delete_restaurant: 'Are you sure you want to delete this restaurant?',
    users: 'Users',
    users_management: 'Users Management',
    create_user: 'Create User',
    user_role: 'Role',
    role_owner: 'Owner',
    role_admin: 'Administrator',
    role_employee: 'Employee',
    confirm_delete_user: 'Are you sure you want to delete this user?',
    no_users_yet: 'No users yet.',
    loading_users: 'Loading users...',
    failed_load_users: 'Failed to load users.',
    change_role: 'Change Role',
    password: 'Password',
    event_type_reservation: 'Reservation',
    event_type_banquet: 'Banquet',
    event_type_wedding: 'Wedding',
    event_type_birthday: 'Birthday',
    event_type_private_party: 'Private Party',
    event_type_corporate: 'Corporate',
    event_type_fotiha_tui: 'Fotiha Tui',
    event_type_nachor_oshi: 'Nachor Oshi',
    birthday_person_name: "Birthday Person's Name",
    birthday_person_name_placeholder: 'First and last name',
    bride_name: "Bride's Name",
    groom_name: "Groom's Name",
    bride_groom_name_placeholder: 'First and last name',
    honoree_person_name: "Name",
    honoree_person_name_placeholder: 'First and last name',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    login_subtitle: 'Sign in to manage events and menu',
    register_subtitle: 'Create a new restaurant owner account',
    username: 'Username',
    username_placeholder: 'Enter your username',
    username_min_length: 'Username must be 3+ characters',
    restaurant_field_label: 'Restaurant',
    restaurant_field_placeholder: 'Your restaurant name',
    restaurant_required: 'Restaurant name is required',
    password_enter_placeholder: 'Enter your password',
    password_create_placeholder: 'Create a strong password',
    signing_in: 'Signing in...',
    creating_account: 'Creating account...',
    first_admin_note: 'First admin to register can always proceed. Later registrations require server setting.',
    confirm_delete_event: 'Delete event for {name}?',
    pw_very_weak: 'Very weak',
    pw_weak: 'Weak',
    pw_fair: 'Fair',
    pw_good: 'Good',
    pw_strong: 'Strong',
    pw_very_strong: 'Very strong',
    pw_req_length: 'At least 8 characters',
    pw_req_upper: 'One uppercase letter',
    pw_req_lower: 'One lowercase letter',
    pw_req_number: 'One number',
    owner_cabinet: 'Owner Cabinet',
    companies: 'Companies',
    new_company: 'New company',
    company_name: 'Company name',
    logo_url: 'Logo URL',
    logo: 'Logo',
    logo_url_hint: 'Logo URL (e.g. /uploads/logo.png)',
    add: 'Add',
    adding: 'Adding...',
    add_restaurant_to: 'Add restaurant to {name}',
    company_logo_used: 'The company logo will be used automatically — no need for a separate restaurant logo.',
    restaurants_in: 'Restaurants in {name}',
    no_companies_yet: 'No companies yet. Create your first one above.',
    all_users: 'All users',
    select_restaurant_dash: '— Select restaurant —',
    restaurant_manager_needs_restaurant: 'A restaurant manager must be assigned a restaurant; its events then feed their expense ledger.',
    administrator_role: 'Administrator',
    employee_role: 'Employee',
    kitchen_role: 'Kitchen',
    owner_role: 'Owner',
    chief_admin_role: 'Chief Admin',
    manager_role: 'Manager',
    catering_admin_role: 'Food Admin',
    restaurant_manager_role: 'Restaurant Manager',
    expense_ledger: 'Expense Ledger',
    expense_ledger_help: 'Track daily allocated funds, product and salary expenses.',
    select_date: 'Select date',
    add_day: 'Add day',
    no_days_yet: 'No days added yet.',
    loading: 'Loading...',
    something_went_wrong: 'Something went wrong.',
    allocated_funds: 'Allocated funds',
    delete_day_confirm: 'Delete this day and all its expenses?',
    product_expenses: 'Product expenses',
    employee_salaries: 'Employee salaries',
    additional_expenses: 'Additional expenses',
    amount_spent: 'Amount spent',
    remaining: 'Remaining',
    budget: 'Budget',
    guests_total: 'Expenses for all guests',
    product_name: 'Product',
    quantity: 'Qty',
    amount: 'Amount',
    employee_name: 'Employee',
    note: 'Note',
    unit_kg: 'kg',
    unit_g: 'g',
    unit_l: 'L',
    unit_ml: 'ml',
    unit_pcs: 'pcs',
    export_pdf: 'Export PDF',
    older_day: 'Previous day',
    newer_day: 'Next day',
    period_day: '1 day',
    period_3_days: '3 days',
    period_week: '1 week',
    period_2_weeks: '2 weeks',
    period_month: '1 month',
    accounts: 'Accounts',
    accounts_help: 'Review every day, close finished days, and download PDF reports.',
    close_day: 'Close day',
    closed_label: 'Closed',
    close_day_confirm: 'Close this day? It will be excluded from PDF downloads.',
    date_from: 'From',
    date_to: 'To',
    closed_excluded_note: 'Closed days are excluded.',
    pdf_days_label: 'Days to include',
    day_report: 'End-of-day report',
    day_report_placeholder: 'Summary of the day...',
    download_close_selected: 'Download & close selected',
    reopen_day: 'Reopen',
    reopen_day_confirm: 'Reopen this day?',
    dept_nahor: 'Nahor',
    dept_fotiha: 'Fotiha',
    dept_tui: 'Wedding',
    dept_others: 'Others',
    or: 'or',
    add_day_for_date: 'For date',
    create_in_advance: 'Create in advance',
    booking: 'Booking',
    booking_name: 'Booking name',
    event_notes: 'Event notes',
    event_notes_placeholder: 'Notes for this department...',
    download_selected: 'Download selected',
    download_additional: 'Download additional',
    go_to_ledger: 'Change',
    additional_expenses_help: 'Other daily expenses, kept separate from the main expenses.',
    delete_company_confirm: 'Delete company "{name}" and all its restaurants?',
    delete_restaurant_confirm: 'Delete {name}? All its data will be lost.',
    delete_user_confirm: 'Delete user {name}?',
    address: 'Address',
    welcome_title: 'Welcome!',
    welcome_intro: 'We are glad to see you today. We hope you will have a pleasant time with us, enjoy the cozy atmosphere, and sample dishes prepared with care and attention to each guest.',
    welcome_help: 'If you need help choosing a dish or drink, our staff is always ready to assist.',
    welcome_bon_appetit: 'We wish you a pleasant stay and bon appétit!',
    welcome_continue: 'Continue',
    calendar: 'Calendar',
    no_halls_to_display: 'No halls available. Create a hall first.',
    booked: 'Booked',
    available: 'Available',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    month_january: 'January',
    month_february: 'February',
    month_march: 'March',
    month_april: 'April',
    month_may: 'May',
    month_june: 'June',
    month_july: 'July',
    month_august: 'August',
    month_september: 'September',
    month_october: 'October',
    month_november: 'November',
    month_december: 'December',
    weekday_mon: 'Mon',
    weekday_tue: 'Tue',
    weekday_wed: 'Wed',
    weekday_thu: 'Thu',
    weekday_fri: 'Fri',
    weekday_sat: 'Sat',
    weekday_sun: 'Sun',
    install_app: 'Install app',
    install_app_desc: 'Add this app to your home screen for faster access.',
    install_ios_hint: 'Tap the Share button and choose "Add to Home Screen".',
    later: 'Later',
    edit_credentials: 'Edit credentials',
    new_username: 'New username',
    new_password: 'New password',
    password_blank_keep: 'Leave blank to keep current',
    credentials_saved: 'Saved',
    devices: 'Devices',
    devices_management: 'Devices & Sessions',
    about_us: 'About Us',
    contact_us: 'Contact Us',
    our_menu: 'Our Menu',
    view_category: 'View',
    back_to_menu: 'Back to menu',
    address_label: 'Address',
    no_dishes_in_category: 'No dishes in this category yet.',
    catering_welcome: 'Welcome! Explore our menu, learn about us, and get in touch.',
    reviews: 'Reviews',
    arrangement: 'Arrangement',
    arrangement_help: 'Drag categories and dishes to set the order they appear on the catering site. Bestsellers always stay at the top of their category.',
    arrangement_admin_help: 'Set the display order of menu categories, dishes, and table categories. Changes apply across the tablet, public site, and selection screens.',
    arrangement_tc_help: 'Drag table categories to set the order they appear in selection screens and the public site.',
    arrangement_categories: 'Category order',
    arrangement_dishes: 'Dishes in this category',
    arrangement_saved: 'Arrangement saved',
    arrangement_save_failed: 'Failed to save arrangement',
    save_arrangement: 'Save arrangement',
    move_up: 'Move up',
    move_down: 'Move down',
    no_dishes: 'No dishes',
    our_history: 'Our Story',
    phone: 'Phone',
    email: 'Email',
    leave_a_review: 'Leave a review',
    your_name: 'Your name',
    your_rating: 'Your rating',
    your_review: 'Your review',
    submit_review: 'Submit review',
    review_thanks: 'Thank you! Your review will appear after moderation.',
    no_reviews_yet: 'No reviews yet. Be the first!',
    back_to_halls: 'Back to halls',
    view_hall: 'View hall',
    hall_gallery: 'Gallery',
    background_photo: 'Background photo',
    background_photo_help: 'Shown as the backdrop of your public catering site.',
    manage_halls: 'Halls',
    hall_info_help: 'Halls and their photos appear on the public catering site.',
    add_hall: 'Add hall',
    no_halls: 'No halls yet.',
    add_photo: 'Add photo',
    seats: 'seats',
    restaurant_info: 'Restaurant info',
    restaurant_info_help: 'This information appears on the public catering site.',
    history_label: 'History / About',
    save_info: 'Save info',
    moderate_reviews: 'Reviews',
    approve: 'Approve',
    unapprove: 'Unapprove',
    approved: 'Approved',
    pending_moderation: 'Pending',
    no_reviews_to_moderate: 'No reviews yet.',
    devices_help: 'These are the devices currently signed in to your account.',
    this_device: 'This device',
    disconnect: 'Disconnect',
    last_active: 'Last active',
    signed_in: 'Signed in',
    no_devices: 'No active devices.',
    unknown_device: 'Unknown device',
    confirm_disconnect_device: 'Disconnect this device? It will be signed out.',
    view_tablet_menu: 'View tablet menu',
    choose_restaurant_to_view: 'Choose a restaurant',
    view_only_mode: 'View-only mode',
    no_restaurants_available: 'No restaurants available.',
    choose_first_course: 'Choose your first course',
    choose_hot_appetizers: 'Choose hot appetizers',
    change_hot_appetizers: 'Change hot appetizers',
    up_to_two: 'Up to 2',
    choose_second_course: 'Choose your second course',
    choose_third_course: 'Choose your third course',
    multi_select: 'multiple choices',
    manager_portal: 'Manager Portal',
    flyers: 'Flyers',
    invitations: 'Invitations',
    new_invitation: 'New invitation',
    no_invitations_yet: 'No invitations yet.',
    responses: 'Responses',
    restaurant_events: 'Restaurant events',
    all_restaurants: 'All restaurants',
    no_events: 'No events.',
    back: 'Back',
    designer: 'Designer',
    block_designer_flyer: 'Flyer Designer',
    block_designer_invitation: 'Invitation Designer',
    add_block: 'Add block',
    choose_block: 'Choose a block',
    block_settings: 'Block settings',
    theme_settings: 'Theme',
    preview: 'Preview',
    publish: 'Publish',
    published_label: 'Published',
    save_changes: 'Save changes',
    create_project: 'Create',
    save_as_template: 'Save as template',
    template_saved: 'Template saved',
    template_name: 'Template name',
    blank: 'Blank',
    start_blank: 'Start blank',
    my_templates: 'My templates',
    ready_made: 'Ready-made',
    no_templates: 'No saved templates yet.',
    delete_block: 'Delete',
    duplicate_block: 'Duplicate',
    animation: 'Animation',
    duration_ms: 'Duration (ms)',
    delay_ms: 'Delay (ms)',
    accent_color: 'Accent color',
    background_color: 'Background color',
    tablet_theme: 'Tablet theme colors',
    tablet_theme_help: 'Set the accent and background colors guests see on the tablet menu and summary pages.',
    reset_theme: 'Reset to default',
    trail: 'Cursor trail',
    trail_color: 'Trail color',
    music: 'Background music',
    add_item: 'Add',
    add_row: 'Add row',
    empty_design: 'No blocks yet — tap “Add block” to begin.',
    block_hero: 'Hero',
    block_heading: 'Heading',
    block_text: 'Text',
    block_image: 'Image',
    block_button: 'Button',
    block_countdown: 'Countdown',
    block_timing: 'Timing',
    block_gallery: 'Gallery',
    block_menu: 'Menu',
    block_socials: 'Socials',
    block_contacts: 'Contacts',
    block_rsvp: 'RSVP',
    block_map: 'Map',
    block_promo: 'Promo',
    block_divider: 'Divider',
    bf_title: 'Title',
    bf_subtitle: 'Subtitle',
    bf_image: 'Image',
    bf_text: 'Text',
    bf_align: 'Alignment',
    bf_label: 'Label',
    bf_action: 'Action',
    bf_datetime: 'Date & time',
    bf_gallery: 'Gallery items',
    bf_timing: 'Schedule rows',
    bf_menu: 'Menu items',
    bf_socials: 'Links',
    bf_phone: 'Phone',
    bf_telegram: 'Telegram URL',
    bf_instagram: 'Instagram URL',
    bf_address: 'Address',
    bf_code: 'Promo code',
    bf_rounded: 'Rounded corners',
    align_left: 'Left',
    align_center: 'Center',
    align_right: 'Right',
    action_link: 'Link',
    action_phone: 'Phone',
    action_telegram: 'Telegram',
    action_map: 'Map (Yandex)',
    action_value: 'Value',
  },
  ru: {
    banquet_admin: 'Админ Банкет',
    events: 'События',
    menu: 'Меню',
    tables: 'Категории столов',
    halls: 'Залы',
    tablet: 'Планшет',
    logout: 'Выйти',
    logging_out: 'Выход...',
    client_menu_selection: 'Выбор меню клиента',
    room_table_settings: 'Нastройки зала и столов',
    select_room: 'Выбрать зал',
    select_table_category: 'Выбрать категорию стола',
    free_for_this_table: 'Бесплатно для этого стола',
    no_table_categories: 'Категорий столов пока нет — создайте сначала',
    guests: 'Гостей',
    choose_room: 'Выберите зал...',
    choose_table_category: 'Выберите категорию стола...',
    selected: 'Выбрано',
    loading_menu: 'Загрузка меню...',
    failed_load_menu: 'Не удалось загрузить меню.',
    real_time_estimate: 'Оценка в реальном времени',
    per_guest: 'На гостя',
    choose_room_table_details: 'Выберите настройки зала и стола',
    browse_menu_items: 'Просмотрите меню и выберите блюда',
    price_per_guest: 'Цена за гостя',
    next_step: 'Следующий шаг',
    review_and_confirm: 'Проверьте выбор перед подтверждением',
    download_failed: 'Не удалось скачать. Пожалуйста, попробуйте снова.',
    enter_customer_information: 'Введите данные клиента для подтверждения заказа',
    overview_of_selection: 'Обзор выбранных данных мероприятия',
    not_selected: 'Не выбрано',
    selected_menu_items: 'Выбранные дополнительные блюда',
    review_selected_dishes: 'Проверьте выбранные блюда',
    no_items_selected: 'Пока нет выбранных пунктов',
    actions: 'Действия',
    event_confirmed: 'Ваше событие подтверждено',
    view_summary: 'Просмотреть итоги',
    change_menu: 'Изменить меню',
    create_menu: 'Создать меню',
    second_customer_name: 'Имя второго лица (необязательно)',
    second_customer_phone: 'Телефон второго лица (необязательно)',
    deposit: 'Залог',
    deposit_optional: 'Залог (необязательно)',
    amount_due: 'К оплате',
    general: 'Общее',
    reschedule: 'Перенести',
    reschedule_event: 'Перенести мероприятие',
    new_date: 'Новая дата',
    new_time: 'Новое время',
    rescheduled_from: 'Перенесено с',
    create_new_event_button: 'Создать мероприятие',
    hide_form: 'Скрыть',
    change_first_course: 'Изменить первое блюдо',
    change_second_course: 'Изменить второе блюдо',
    change_third_course: 'Изменить третье блюдо',
    collapse_options: 'Свернуть',
    included_dishes: 'Включённые блюда',
    differences_highlighted: 'Отличия выделены',
    customer_information: 'Информация о клиенте',
    notifications: 'Уведомления',
    no_notifications: 'Нет уведомлений',
    overdue_debts_subtitle: 'Непогашенные долги с истёкшим сроком',
    debt: 'Долг',
    debt_overdue: 'Долг просрочен',
    debt_overdue_notice: 'Непогашенный долг: {amount}',
    debt_deadline: 'Срок погашения долга',
    payment: 'Платёж',
    payment_amount: 'Сумма платежа',
    add_payment: 'Добавить платёж',
    edit_menu: 'Изменить меню',
    selection_summary: 'Итоговый выбор',
    menu_for_banquet: 'МЕНЮ НА БАНКЕТ',
    dish_name: 'Наименование',
    qty_pcs: 'Количество (шт)',
    date: 'Дата',
    customer_details: 'Данные клиента',
    customer_name: 'Имя',
    customer_phone: 'Телефон',
    event_details: 'Данные мероприятия',
    hall: 'Зал',
    table_category: 'Категория стола',
    guest_count: 'Количество гостей',
    selected_dishes: 'Выбранные блюда',
    additional_dishes: 'Дополнительные блюда',
    table_category_dishes: 'Блюда категории стола',
    pricing: 'Ценообразование',
    subtotal: 'Промежуточный итог',
    tax: 'Налог',
    total: 'Итого',
    price_per_person: 'Цена на человека',
    summary: 'Итог',
    thank_you: 'Спасибо за выбор наших банкетных услуг. Ваш выбор был зафиксирован.',
    total_guests: 'Всего гостей',
    estimated_total: 'Ориентировочная сумма',
    edit_selection: 'Редактировать выбор',
    confirm: 'Подтвердить',
    download_pdf: 'Скачать PDF',
    download_excel: 'Скачать Excel',
    language: 'Язык',
    english: 'English',
    translations: 'Переводы',
    translations_hint: 'Необязательно — показывается на планшете и сайте кейтеринга для каждого языка. По умолчанию используется основной текст.',
    russian: 'Русский',
    uzbek: 'O\'zbekcha',
    banquet_events: 'Банкетные события',
    create_new_event: 'Создать новое событие',
    edit_existing_event: 'Редактировать существующее событие',
    phone_number: 'Номер телефона',
    event_date_time: 'Дата/время события',
    event_type: 'Тип события',
    status: 'Статус',
    hall_optional: 'Зал (Необязательно)',
    table_category_optional: 'Категория стола (Необязательно)',
    notes: 'Заметки',
    create_event: 'Создать событие',
    creating: 'Создание...',
    update_event: 'Обновить событие',
    updating: 'Обновление...',
    cancel: 'Отмена',
    loading_events: 'Загрузка событий...',
    failed_load_events: 'Не удалось загрузить события.',
    invoices: 'Счета',
    invoice_one: 'счёт',
    invoice_many: 'счетов',
    invoices_open: 'Открытые',
    invoices_outstanding: 'С задолженностью',
    invoices_paid: 'Оплаченные',
    billable_total: 'Итого к оплате',
    table_package: 'Пакет стола',
    round_up_to_million: 'Округлить вниз до миллиона',
    rounded_to_million: 'Округлено вниз до ближайшего миллиона',
    close_invoice: 'Закрыть счёт',
    closing: 'Закрытие…',
    invoice_closed: 'Закрыт',
    no_invoices: 'Пока нет событий для выставления счёта.',
    status_draft: 'Черновик',
    status_confirmed: 'Подтверждён',
    status_cancelled: 'Отменён',
    status_completed: 'Завершён',
    status_menu_not_selected: 'Меню не выбрано',
    ev_col_customer: 'Клиент',
    ev_col_datetime: 'Дата / Время',
    ev_col_hall_table: 'Зал / Стол',
    no_events_yet: 'Событий пока нет.',
    dishes_count: '{count} блюд',
    dish_count_one: '1 блюдо',
    pcs_total: 'всего {count} шт.',
    hidden_label: 'Скрыто',
    do_not_show: 'Не показывать',
    show_subcategory: 'Показать',
    disable_subcategories: 'Отключить подкатегории',
    disable_subcategories_help: 'Главный переключатель — когда включён, подкатегории отключаются везде: столбец «Подкатегория» в меню скрывается, а на сайте кейтеринга не показываются заголовки подкатегорий, независимо от отдельных подкатегорий ниже.',
    subcategories_enabled: 'Подкатегории вкл.',
    subcategories_disabled: 'Подкатегории выкл.',
    more: 'Ещё',
    settings: 'Настройки',
    excluded_categories: 'Исключённые категории блюд',
    excluded_categories_help: 'Отмеченные категории недоступны и скрыты везде — в меню, категориях столов и фотографиях. Их блюда остаются сохранёнными и снова появятся, если снять отметку.',
    excluded_count: 'Исключено категорий: {count}',
    nothing_excluded: 'Ни одна категория не исключена — доступно всё.',
    save_settings: 'Сохранить настройки',
    settings_saved: 'Настройки сохранены.',
    settings_save_failed: 'Не удалось сохранить настройки.',
    select_hall: '-- Выберите зал --',
    menu_management: 'Управление меню',
    create_menu_item: 'Создать пункт меню',
    name: 'Название',
    name_optional: 'Название (необязательно)',
    blank_uses_company_name: 'Оставьте пустым, чтобы использовать название компании.',
    description: 'Описание',
    category: 'Категория',
    price: 'Цена',
    photo_url: 'URL фото',
    create: 'Создать',
    update: 'Обновить',
    delete: 'Удалить',
    deleting: 'Удаление...',
    active: 'Активен',
    inactive: 'Неактивен',
    cold_appetizers: 'Холодные закуски',
    hot_appetizers: 'Горячие закуски',
    your_selection: 'Ваш выбор',
    assorted: 'Ассорти',
    salads: 'Салаты',
    first_course: 'Первое блюдо',
    second_course: 'Второе блюдо',
    third_course: 'Третье блюдо',
    drinks: 'Напитки',
    sweets: 'Десерты',
    fruits: 'Фрукты',
    soups: 'Супы',
    pizza: 'Пицца',
    grill: 'Мангал',
    pastry: 'Выпечка',
    beer_snacks: 'К пиву',
    dessert: 'Десерт',
    lamb_dishes: 'Блюда из баранины',
    beef_dishes: 'Блюда из говядины',
    chicken_dishes: 'Блюда из курицы',
    side_dishes: 'Гарниры',
    pasta: 'Паста',
    soft_drinks: 'Прохладительные напитки',
    steaks: 'Стейки',
    energy_drinks: 'Энергетики',
    salads_oil: 'Салаты на масляной основе',
    salads_mayo: 'Салаты на майонезной основе',
    coffee: 'Кофемания',
    sushi_rolls: 'Суши и роллы',
    dried_fruits: 'Сухофрукты',
    candies: 'Конфеты',
    alcohol: 'Алкоголь',
    lemonades: 'Лимонады',
    non_alcoholic_cocktails: 'Безалкогольные коктейли',
    alcoholic_cocktails: 'Алкогольные коктейли',
    milkshakes: 'Молочные коктейли',
    tea_menu: 'Чайная карта',
    fresh_juices: 'Свежевыжатые соки',
    liqueurs: 'Ликёры',
    filter_all: 'Все',
    food_package: 'Пакет питания',
    included_with_table: 'Включено в ваш стол',
    servings_per_table: 'Порций на стол',
    courses: 'Первое и второе блюдо',
    additional: 'Дополнительно',
    additional_management: 'Дополнительные блюда',
    additional_help: 'Задайте статус каждого блюда: «Платно» — показывать как платное дополнительное блюдо на планшете, «Бесплатно» — разрешить гостям бесплатную замену включённых блюд, «Не показывать» — скрыть из обоих списков.',
    status_dont_show: 'Не показывать',
    status_free: 'Бесплатно',
    status_paid: 'Платно',
    swap_free: 'Бесплатная замена',
    choose_replacement: 'Выберите замену',
    included_default: 'включено',
    revert_to_default: 'Вернуть блюдо по умолчанию',
    table_type: 'Тип стола',
    table_type_adult: 'Взрослый стол',
    table_type_children: 'Детский стол',
    children_table: 'Детский стол',
    add_children_table: 'Добавить детский стол',
    children_table_included: 'Детский стол добавлен',
    children_count: 'Количество детей',
    subcategories: 'Подкатегории',
    subcategory: 'Подкатегория',
    subcategories_help: 'Создавайте подкатегории, чтобы разделить каждую категорию блюд на разделы на сайте кейтеринга.',
    create_subcategory: 'Создать подкатегорию',
    subcategory_name: 'Название подкатегории',
    add_subcategory: 'Добавить подкатегорию',
    no_subcategories_yet: 'Пока нет подкатегорий.',
    no_subcategory: 'Без подкатегории',
    delete_subcategory_confirm: 'Удалить эту подкатегорию?',
    other: 'Другое',
    show_on_tablet: 'Показано на планшете',
    bestseller: 'Хит продаж',
    bestsellers_only: 'Только хиты продаж',
    out_of_stock: 'Нет в наличии',
    attach_photo: 'Прикрепить фото',
    shown: 'Показано',
    hidden: 'Скрыто',
    discount: 'Скидка',
    discount_percent: 'Скидка (%)',
    apply_discount: 'Применить скидку',
    original_price: 'Цена без скидки',
    discounted_price: 'Цена со скидкой',
    no_additional_dishes: 'Пока нет дополнительных блюд. Добавьте их на странице Меню.',
    table_categories_management: 'Управление категориями столов',
    create_table_category: 'Создать категорию стола',
    seating_capacity: 'Вместимость',
    meal_package: 'Пакет питания',
    rate_per_person: 'Цена на человека',
    table_category_name_placeholder: 'например, стол на 2 человек',
    photo_url_optional: 'URL фото (Необязательно)',
    description_optional: 'Описание (Необязательно)',
    required: 'Обязательно',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Создать категорию',
    failed_to_create_category: 'Не удалось создать категорию.',
    loading_table_categories: 'Загрузка категорий столов...',
    failed_to_load_table_categories: 'Не удалось загрузить категории столов.',
    all_categories: 'Все категории',
    no_table_categories_yet: 'Категорий столов пока нет.',
    capacity: 'Вместимость',
    meal: 'Питание',
    rate: 'Ставка',
    rate_dollar: 'Ставка ($)',
    saving: 'Сохранение...',
    save: 'Сохранить',
    edit: 'Редактировать',
    halls_management: 'Управление залами',
    create_hall: 'Создать зал',
    hall_name_placeholder: 'например, Главный зал',
    create_hall_button: 'Создать зал',
    failed_to_create_hall: 'Не удалось создать зал.',
    loading_halls: 'Загрузка залов...',
    failed_to_load_halls: 'Не удалось загрузить залы.',
    all_halls: 'Все залы',
    no_halls_yet: 'Залов пока нет.',
    hall_capacity: 'Вместимость',
    hall_description: 'Описание',
    hall_photo_url: 'URL фото',
    hall_active: 'Активен',
    hall_inactive: 'Неактивен',
    photos: 'Фотографии',
    photo_management: 'Управление фотографиями',
    upload_photos: 'Загрузить фотографии',
    photo_category: 'Категория фотографий',
    menu_photos: 'Фотографии меню',
    hall_photos: 'Фотографии залов',
    table_photos: 'Фотографии столов',
    table_categories: 'Категории столов',
    select_table: 'Выбрать этот стол',
    person: 'чел.',
    dish_category: 'Категория блюда',
    select_upload_files: 'Выбрать файлы',
    uploading: 'Загрузка...',
    upload_photos_help: 'Загружайте изображения для управления фотографиями меню, залов и столов. Макс 5 МБ на файл.',
    loading_photos: 'Загрузка фотографий...',
    failed_load_photos: 'Не удалось загрузить фотографии.',
    no_photos_uploaded: 'Фотографии еще не загружены.',
    confirm_delete_photo: 'Вы уверены, что хотите удалить эту фотографию?',
    select_menu_photo: 'Выберите фотографию для пункта меню',
    select_hall_photo: 'Выберите фотографию для зала',
    select_table_photo: 'Выберите фотографию для категории стола',
    selected_photo: 'Выбрано',
    clear_selection: 'Очистить',
    search_event_by_id: 'Поиск события по ID',
    enter_event_id: 'Введите ID события',
    search: 'Поиск',
    search_olog_n: 'Поиск',
    event_not_found: 'Событие с ID {id} не найдено',
    search_result: 'Результат поиска',
    no_events_loaded: 'События не загружены',
    start_new_booking: 'Новое бронирование',
    submitting: 'Отправка...',
    event_create_error: 'Не удалось создать событие. Попробуйте ещё раз.',
    notes_placeholder: 'Особые пожелания или комментарии...',
    event_date: 'Дата события',
    event_time: 'Время события',
    select_restaurant: 'Выберите ресторан',
    my_restaurants: 'Мои рестораны',
    restaurants_management: 'Мои рестораны',
    create_restaurant: 'Создать ресторан',
    restaurant_name: 'Название ресторана',
    restaurant_address: 'Адрес',
    restaurant_logo_url: 'URL логотипа',
    restaurant_name_placeholder: 'например, Банкет Мадинабек',
    restaurant_address_placeholder: 'например, ул. Главная 12, Ташкент',
    no_restaurants_yet: 'Ресторанов пока нет. Создайте первый.',
    loading_restaurants: 'Загрузка ресторанов...',
    failed_load_restaurants: 'Не удалось загрузить рестораны.',
    confirm_delete_restaurant: 'Вы уверены, что хотите удалить этот ресторан?',
    users: 'Пользователи',
    users_management: 'Управление пользователями',
    create_user: 'Создать пользователя',
    user_role: 'Роль',
    role_owner: 'Владелец',
    role_admin: 'Администратор',
    role_employee: 'Сотрудник',
    confirm_delete_user: 'Вы уверены, что хотите удалить этого пользователя?',
    no_users_yet: 'Пользователей пока нет.',
    loading_users: 'Загрузка пользователей...',
    failed_load_users: 'Не удалось загрузить пользователей.',
    change_role: 'Изменить роль',
    password: 'Пароль',
    event_type_reservation: 'Бронирование',
    event_type_banquet: 'Банкет',
    event_type_wedding: 'Свадьба',
    event_type_birthday: 'День рождения',
    event_type_private_party: 'Частная вечеринка',
    event_type_corporate: 'Корпоратив',
    event_type_fotiha_tui: 'Фотиха Туй',
    event_type_nachor_oshi: 'Нахор Оши',
    birthday_person_name: 'Имя именинника',
    birthday_person_name_placeholder: 'Имя и фамилия',
    bride_name: 'Имя невесты',
    groom_name: 'Имя жениха',
    bride_groom_name_placeholder: 'Имя и фамилия',
    honoree_person_name: 'Имя',
    honoree_person_name_placeholder: 'Имя и фамилия',
    sign_in: 'Войти',
    create_account: 'Создать аккаунт',
    login_subtitle: 'Войдите для управления событиями и меню',
    register_subtitle: 'Создайте аккаунт владельца ресторана',
    username: 'Имя пользователя',
    username_placeholder: 'Введите имя пользователя',
    username_min_length: 'Минимум 3 символа',
    restaurant_field_label: 'Ресторан',
    restaurant_field_placeholder: 'Название вашего ресторана',
    restaurant_required: 'Название ресторана обязательно',
    password_enter_placeholder: 'Введите пароль',
    password_create_placeholder: 'Создайте надёжный пароль',
    signing_in: 'Вход...',
    creating_account: 'Создание аккаунта...',
    first_admin_note: 'Первый зарегистрированный администратор всегда может пройти. Последующие регистрации требуют настройки сервера.',
    confirm_delete_event: 'Удалить событие для {name}?',
    pw_very_weak: 'Очень слабый',
    pw_weak: 'Слабый',
    pw_fair: 'Удовлетворительный',
    pw_good: 'Хороший',
    pw_strong: 'Надёжный',
    pw_very_strong: 'Очень надёжный',
    pw_req_length: 'Минимум 8 символов',
    pw_req_upper: 'Одна заглавная буква',
    pw_req_lower: 'Одна строчная буква',
    pw_req_number: 'Одна цифра',
    owner_cabinet: 'Кабинет владельца',
    companies: 'Компании',
    new_company: 'Новая компания',
    company_name: 'Название компании',
    logo_url: 'URL логотипа',
    logo: 'Логотип',
    logo_url_hint: 'URL логотипа (например /uploads/logo.png)',
    add: 'Добавить',
    adding: 'Добавление...',
    add_restaurant_to: 'Добавить ресторан в {name}',
    company_logo_used: 'Логотип компании будет использован автоматически — отдельный логотип ресторана не нужен.',
    restaurants_in: 'Рестораны в {name}',
    no_companies_yet: 'Пока нет компаний. Создайте первую выше.',
    all_users: 'Все пользователи',
    select_restaurant_dash: '— Выберите ресторан —',
    restaurant_manager_needs_restaurant: 'Менеджер ресторана должен быть привязан к ресторану; его события затем попадают в учёт расходов.',
    administrator_role: 'Администратор',
    employee_role: 'Сотрудник',
    kitchen_role: 'Кухня',
    owner_role: 'Владелец',
    chief_admin_role: 'Главный администратор',
    manager_role: 'Менеджер',
    catering_admin_role: 'Фуд-администратор',
    restaurant_manager_role: 'Менеджер ресторана',
    expense_ledger: 'Книга расходов',
    expense_ledger_help: 'Учёт выделенных средств, расходов на продукты и зарплаты по дням.',
    select_date: 'Выберите дату',
    add_day: 'Добавить день',
    no_days_yet: 'Дни ещё не добавлены.',
    loading: 'Загрузка...',
    something_went_wrong: 'Что-то пошло не так.',
    allocated_funds: 'Выделено средств',
    delete_day_confirm: 'Удалить этот день и все его расходы?',
    product_expenses: 'Расходы на продукты',
    employee_salaries: 'Зарплаты сотрудников',
    additional_expenses: 'Дополнительные расходы',
    amount_spent: 'Потрачено',
    remaining: 'Остаток',
    budget: 'Бюджет',
    guests_total: 'Расходы на всех гостей',
    product_name: 'Продукт',
    quantity: 'Кол-во',
    amount: 'Сумма',
    employee_name: 'Сотрудник',
    note: 'Примечание',
    unit_kg: 'кг',
    unit_g: 'г',
    unit_l: 'л',
    unit_ml: 'мл',
    unit_pcs: 'шт',
    export_pdf: 'Экспорт PDF',
    older_day: 'Предыдущий день',
    newer_day: 'Следующий день',
    period_day: '1 день',
    period_3_days: '3 дня',
    period_week: '1 неделя',
    period_2_weeks: '2 недели',
    period_month: '1 месяц',
    accounts: 'Счета',
    accounts_help: 'Просматривайте дни, закрывайте завершённые и скачивайте PDF-отчёты.',
    close_day: 'Закрыть день',
    closed_label: 'Закрыт',
    close_day_confirm: 'Закрыть этот день? Он будет исключён из выгрузки PDF.',
    date_from: 'С',
    date_to: 'По',
    closed_excluded_note: 'Закрытые дни исключены.',
    pdf_days_label: 'Количество дней',
    day_report: 'Отчёт за день',
    day_report_placeholder: 'Итоги дня...',
    download_close_selected: 'Скачать и закрыть выбранные',
    reopen_day: 'Открыть заново',
    reopen_day_confirm: 'Открыть этот день заново?',
    dept_nahor: 'Нахор',
    dept_fotiha: 'Фотиха',
    dept_tui: 'Свадьба',
    dept_others: 'Прочее',
    or: 'или',
    add_day_for_date: 'На дату',
    create_in_advance: 'Создать заранее',
    booking: 'Бронь',
    booking_name: 'Название брони',
    event_notes: 'Заметки события',
    event_notes_placeholder: 'Заметки по этому отделу...',
    download_selected: 'Скачать выбранные',
    download_additional: 'Скачать доп. расходы',
    go_to_ledger: 'Изменить',
    additional_expenses_help: 'Прочие ежедневные расходы, отдельно от основных.',
    delete_company_confirm: 'Удалить компанию «{name}» и все её рестораны?',
    delete_restaurant_confirm: 'Удалить {name}? Все её данные будут потеряны.',
    delete_user_confirm: 'Удалить пользователя {name}?',
    address: 'Адрес',
    welcome_title: 'Добро пожаловать!',
    welcome_intro: 'Мы рады видеть вас сегодня. Надеемся, вы приятно проведёте у нас время, насладитесь уютной атмосферой и попробуете блюда, приготовленные с заботой и вниманием к каждому гостю.',
    welcome_help: 'Если вам понадобится помощь в выборе блюда или напитка, наш персонал всегда готов помочь.',
    welcome_bon_appetit: 'Желаем вам приятного отдыха и приятного аппетита!',
    welcome_continue: 'Продолжить',
    calendar: 'Календарь',
    no_halls_to_display: 'Залов нет. Сначала создайте зал.',
    booked: 'Занято',
    available: 'Свободно',
    breakfast: 'Завтрак',
    lunch: 'Обед',
    dinner: 'Ужин',
    month_january: 'Январь',
    month_february: 'Февраль',
    month_march: 'Март',
    month_april: 'Апрель',
    month_may: 'Май',
    month_june: 'Июнь',
    month_july: 'Июль',
    month_august: 'Август',
    month_september: 'Сентябрь',
    month_october: 'Октябрь',
    month_november: 'Ноябрь',
    month_december: 'Декабрь',
    weekday_mon: 'Пн',
    weekday_tue: 'Вт',
    weekday_wed: 'Ср',
    weekday_thu: 'Чт',
    weekday_fri: 'Пт',
    weekday_sat: 'Сб',
    weekday_sun: 'Вс',
    install_app: 'Установить приложение',
    install_app_desc: 'Добавьте приложение на главный экран для быстрого доступа.',
    install_ios_hint: 'Нажмите кнопку «Поделиться» и выберите «На экран Домой».',
    later: 'Позже',
    edit_credentials: 'Изменить данные',
    new_username: 'Новый логин',
    new_password: 'Новый пароль',
    password_blank_keep: 'Оставьте пустым, чтобы не менять',
    credentials_saved: 'Сохранено',
    devices: 'Устройства',
    devices_management: 'Устройства и сеансы',
    about_us: 'О нас',
    contact_us: 'Контакты',
    our_menu: 'Наше меню',
    view_category: 'Открыть',
    back_to_menu: 'Назад в меню',
    address_label: 'Адрес',
    no_dishes_in_category: 'В этой категории пока нет блюд.',
    catering_welcome: 'Добро пожаловать! Ознакомьтесь с нашим меню, узнайте о нас и свяжитесь с нами.',
    reviews: 'Отзывы',
    arrangement: 'Расположение',
    arrangement_help: 'Перетаскивайте категории и блюда, чтобы задать порядок их отображения на сайте кейтеринга. Хиты продаж всегда остаются вверху своей категории.',
    arrangement_admin_help: 'Задайте порядок отображения категорий меню, блюд и категорий столов. Изменения применяются на планшете, публичном сайте и экранах выбора.',
    arrangement_tc_help: 'Перетаскивайте категории столов, чтобы задать порядок их отображения на экранах выбора и публичном сайте.',
    arrangement_categories: 'Порядок категорий',
    arrangement_dishes: 'Блюда в этой категории',
    arrangement_saved: 'Расположение сохранено',
    arrangement_save_failed: 'Не удалось сохранить расположение',
    save_arrangement: 'Сохранить расположение',
    move_up: 'Вверх',
    move_down: 'Вниз',
    no_dishes: 'Нет блюд',
    our_history: 'Наша история',
    phone: 'Телефон',
    email: 'Эл. почта',
    leave_a_review: 'Оставить отзыв',
    your_name: 'Ваше имя',
    your_rating: 'Ваша оценка',
    your_review: 'Ваш отзыв',
    submit_review: 'Отправить отзыв',
    review_thanks: 'Спасибо! Ваш отзыв появится после модерации.',
    no_reviews_yet: 'Пока нет отзывов. Будьте первым!',
    back_to_halls: 'Назад к залам',
    view_hall: 'Открыть зал',
    hall_gallery: 'Галерея',
    background_photo: 'Фоновое фото',
    background_photo_help: 'Используется как фон публичного сайта.',
    manage_halls: 'Залы',
    hall_info_help: 'Залы и их фотографии отображаются на публичном сайте.',
    add_hall: 'Добавить зал',
    no_halls: 'Пока нет залов.',
    add_photo: 'Добавить фото',
    seats: 'мест',
    restaurant_info: 'Данные ресторана',
    restaurant_info_help: 'Эта информация отображается на публичном сайте.',
    history_label: 'История / О нас',
    save_info: 'Сохранить',
    moderate_reviews: 'Отзывы',
    approve: 'Одобрить',
    unapprove: 'Скрыть',
    approved: 'Одобрен',
    pending_moderation: 'На модерации',
    no_reviews_to_moderate: 'Отзывов пока нет.',
    devices_help: 'Это устройства, на которых сейчас выполнен вход в вашу учётную запись.',
    this_device: 'Это устройство',
    disconnect: 'Отключить',
    last_active: 'Последняя активность',
    signed_in: 'Вход выполнен',
    no_devices: 'Нет активных устройств.',
    unknown_device: 'Неизвестное устройство',
    confirm_disconnect_device: 'Отключить это устройство? Сеанс будет завершён.',
    view_tablet_menu: 'Просмотр меню',
    choose_restaurant_to_view: 'Выберите ресторан',
    view_only_mode: 'Режим просмотра',
    no_restaurants_available: 'Нет доступных ресторанов.',
    choose_first_course: 'Выберите первое блюдо',
    choose_hot_appetizers: 'Выберите горячие закуски',
    change_hot_appetizers: 'Изменить горячие закуски',
    up_to_two: 'До 2',
    choose_second_course: 'Выберите второе блюдо',
    choose_third_course: 'Выберите третье блюдо',
    multi_select: 'несколько вариантов',
    manager_portal: 'Портал менеджера',
    flyers: 'Флаеры',
    invitations: 'Приглашения',
    new_invitation: 'Новое приглашение',
    no_invitations_yet: 'Пока нет приглашений.',
    responses: 'Ответы',
    restaurant_events: 'События ресторана',
    all_restaurants: 'Все рестораны',
    no_events: 'Нет событий.',
    back: 'Назад',
    designer: 'Дизайнер',
    block_designer_flyer: 'Дизайнер флаера',
    block_designer_invitation: 'Дизайнер приглашения',
    add_block: 'Добавить блок',
    choose_block: 'Выберите блок',
    block_settings: 'Настройки блока',
    theme_settings: 'Тема',
    preview: 'Предпросмотр',
    publish: 'Опубликовать',
    published_label: 'Опубликовано',
    save_changes: 'Сохранить изменения',
    create_project: 'Создать',
    save_as_template: 'Сохранить как шаблон',
    template_saved: 'Шаблон сохранён',
    template_name: 'Название шаблона',
    blank: 'Пустой',
    start_blank: 'Начать с пустого',
    my_templates: 'Мои шаблоны',
    ready_made: 'Готовый',
    no_templates: 'Пока нет сохранённых шаблонов.',
    delete_block: 'Удалить',
    duplicate_block: 'Дублировать',
    animation: 'Анимация',
    duration_ms: 'Длительность (мс)',
    delay_ms: 'Задержка (мс)',
    accent_color: 'Акцентный цвет',
    background_color: 'Цвет фона',
    tablet_theme: 'Цвета планшета',
    tablet_theme_help: 'Задайте акцентный цвет и цвет фона, которые гости видят на страницах меню и итога на планшете.',
    reset_theme: 'Сбросить по умолчанию',
    trail: 'След курсора',
    trail_color: 'Цвет следа',
    music: 'Фоновая музыка',
    add_item: 'Добавить',
    add_row: 'Добавить строку',
    empty_design: 'Пока нет блоков — нажмите «Добавить блок».',
    block_hero: 'Обложка',
    block_heading: 'Заголовок',
    block_text: 'Текст',
    block_image: 'Изображение',
    block_button: 'Кнопка',
    block_countdown: 'Таймер',
    block_timing: 'Программа',
    block_gallery: 'Галерея',
    block_menu: 'Меню',
    block_socials: 'Соцсети',
    block_contacts: 'Контакты',
    block_rsvp: 'Подтверждение',
    block_map: 'Карта',
    block_promo: 'Промо',
    block_divider: 'Разделитель',
    bf_title: 'Заголовок',
    bf_subtitle: 'Подзаголовок',
    bf_image: 'Изображение',
    bf_text: 'Текст',
    bf_align: 'Выравнивание',
    bf_label: 'Надпись',
    bf_action: 'Действие',
    bf_datetime: 'Дата и время',
    bf_gallery: 'Элементы галереи',
    bf_timing: 'Строки программы',
    bf_menu: 'Блюда меню',
    bf_socials: 'Ссылки',
    bf_phone: 'Телефон',
    bf_telegram: 'Ссылка Telegram',
    bf_instagram: 'Ссылка Instagram',
    bf_address: 'Адрес',
    bf_code: 'Промокод',
    bf_rounded: 'Скруглённые углы',
    align_left: 'Слева',
    align_center: 'По центру',
    align_right: 'Справа',
    action_link: 'Ссылка',
    action_phone: 'Телефон',
    action_telegram: 'Telegram',
    action_map: 'Карта (Яндекс)',
    action_value: 'Значение',
  },
  uz: {
    banquet_admin: 'Banket Maʼmuri',
    events: 'Tadbirlar',
    menu: 'Menyu',
    tables: 'Jadval Toifalari',
    halls: 'Zallar',
    tablet: 'Planshet',
    logout: 'Chiqish',
    logging_out: 'Chiqilmoqda...',
    client_menu_selection: 'Mijoz menyusi tanlovi',
    room_table_settings: 'Zal va stol sozlamalari',
    select_room: 'Zalni tanlang',
    select_table_category: 'Stol kategoriyasini tanlang',
    free_for_this_table: 'Bu stol uchun bepul',
    no_table_categories: 'Stol kategoriyalari yoq — avval bittasini yarating',
    guests: 'Mehmonlar',
    choose_room: 'Zalni tanlang...',
    choose_table_category: 'Stol kategoriyasini tanlang...',
    selected: 'Tanlangan',
    loading_menu: 'Menyu yuklanmoqda...',
    failed_load_menu: 'Menyu yuklanmadi.',
    real_time_estimate: 'Real vaqtdagi taxmin',
    per_guest: 'Har bir kishi uchun',
    choose_room_table_details: 'Zal va stol sozlamalarini tanlang',
    browse_menu_items: 'Menyu bo\'limlarini ko\'rib chiqing va taomlarni tanlang',
    price_per_guest: 'Bir mehmon uchun narx',
    next_step: 'Keyingi qadam',
    review_and_confirm: 'Tanlovni tasdiqlashdan oldin tekshiring',
    download_failed: 'Yuklab olish muvaffaqiyatsiz tugadi. Iltimos, qayta urinib ko\'ring.',
    enter_customer_information: 'Buyurtmani tasdiqlash uchun mijoz maʼlumotlarini kiriting',
    overview_of_selection: 'Tanlangan tadbir tafsilotlari bo\'yicha umumiy maʼlumot',
    not_selected: 'Tanlanmagan',
    selected_menu_items: 'Tanlangan qo\'shimcha taomlar',
    review_selected_dishes: 'Tanlangan taomlarni tekshiring',
    no_items_selected: 'Hali hech qanday element tanlanmagan',
    actions: 'Harakatlar',
    event_confirmed: 'Sizning tadbiringiz tasdiqlandi',
    view_summary: 'Yakunni ko\'rish',
    change_menu: 'Menyuni o\'zgartirish',
    create_menu: 'Menyu yaratish',
    second_customer_name: 'Ikkinchi shaxs ismi (ixtiyoriy)',
    second_customer_phone: 'Ikkinchi shaxs telefoni (ixtiyoriy)',
    deposit: 'Zakalat',
    deposit_optional: 'Zakalat (ixtiyoriy)',
    amount_due: 'Tolov uchun',
    general: 'Umumiy',
    reschedule: 'Kochirish',
    reschedule_event: 'Tadbirni kochirish',
    new_date: 'Yangi sana',
    new_time: 'Yangi vaqt',
    rescheduled_from: 'Kochirilgan sana',
    create_new_event_button: 'Tadbir yaratish',
    hide_form: 'Yashirish',
    change_first_course: 'Birinchi taomni ozgartirish',
    change_second_course: 'Ikkinchi taomni ozgartirish',
    change_third_course: 'Uchinchi taomni ozgartirish',
    collapse_options: 'Yigish',
    included_dishes: 'Kiritilgan taomlar',
    differences_highlighted: 'Farqlar ajratib korsatilgan',
    customer_information: 'Mijoz malumotlari',
    notifications: 'Bildirishnomalar',
    no_notifications: 'Bildirishnomalar yoq',
    overdue_debts_subtitle: 'Muddati otgan tolanmagan qarzlar',
    debt: 'Qarz',
    debt_overdue: 'Qarz muddati otgan',
    debt_overdue_notice: 'Tolanmagan qarz: {amount}',
    debt_deadline: 'Qarzni tolash muddati',
    payment: 'Tolov',
    payment_amount: 'Tolov summasi',
    add_payment: 'Tolov qoshish',
    edit_menu: 'Menyuni tahrirlash',
    selection_summary: 'Tanlov bo\'yicha yakun',
    menu_for_banquet: 'BANKET MENYUSI',
    dish_name: 'Taom nomi',
    qty_pcs: 'Miqdor (dona)',
    date: 'Sana',
    customer_details: 'Mijoz maʼlumotlari',
    customer_name: 'Ism',
    customer_phone: 'Telefon',
    event_details: 'Tadbir maʼlumotlari',
    hall: 'Zal',
    table_category: 'Stol kategoriyasi',
    guest_count: 'Mehmonlar soni',
    selected_dishes: 'Tanlangan taomlar',
    additional_dishes: 'Qo\'shimcha taomlar',
    table_category_dishes: 'Stol toifasi taomlari',
    pricing: 'Narx hisoboti',
    subtotal: 'Jami',
    tax: 'Soliq',
    total: 'Umumiy summa',
    price_per_person: 'Bir kishi uchun narx',
    summary: 'Xulosa',
    thank_you: 'Banket xizmatlarimizni tanlaganingiz uchun rahmat. Sizning tanlovingiz qayd etildi.',
    total_guests: 'Jami mehmonlar',
    estimated_total: 'Taxminiy umumiy summa',
    edit_selection: 'Tanlovni tahrirlash',
    confirm: 'Tasdiqlash',
    download_pdf: 'PDF yuklab olish',
    download_excel: 'Excel yuklab olish',
    language: 'Til',
    english: 'English',
    translations: 'Tarjimalar',
    translations_hint: 'Ixtiyoriy — planshet va katering saytida har bir til uchun korsatiladi. Asosiy matnga qaytadi.',
    russian: 'Русский',
    uzbek: 'O\'zbekcha',
    banquet_events: 'Banket tadbirlari',
    create_new_event: 'Yangi tadbir yaratish',
    edit_existing_event: 'Mavjud tadbirni tahrirlash',
    phone_number: 'Telefon raqami',
    event_date_time: 'Tadbir sanasi/vaqti',
    event_type: 'Tadbir turi',
    status: 'Holat',
    hall_optional: 'Zal (Ixtiyoriy)',
    table_category_optional: 'Stol kategoriyasi (Ixtiyoriy)',
    notes: 'Izohlar',
    create_event: 'Tadbir yaratish',
    creating: 'Yaratilmoqda...',
    update_event: 'Tadbirni yangilash',
    updating: 'Yangilanmoqda...',
    cancel: 'Bekor qilish',
    loading_events: 'Tadbirlar yuklanmoqda...',
    failed_load_events: 'Tadbirlar yuklanmadi.',
    invoices: 'Hisob-fakturalar',
    invoice_one: 'hisob-faktura',
    invoice_many: 'hisob-faktura',
    invoices_open: 'Ochiq',
    invoices_outstanding: 'Qarzdor',
    invoices_paid: 'To\'langan',
    billable_total: 'Jami to\'lov',
    table_package: 'Stol paketi',
    round_up_to_million: 'Milliongacha pastga yaxlitlash',
    rounded_to_million: 'Eng yaqin milliongacha pastga yaxlitlandi',
    close_invoice: 'Hisobni yopish',
    closing: 'Yopilmoqda…',
    invoice_closed: 'Yopilgan',
    no_invoices: 'Hozircha hisob-faktura uchun tadbirlar yo\'q.',
    status_draft: 'Qoralama',
    status_confirmed: 'Tasdiqlangan',
    status_cancelled: 'Bekor qilingan',
    status_completed: 'Yakunlangan',
    status_menu_not_selected: 'Menyu tanlanmagan',
    ev_col_customer: 'Mijoz',
    ev_col_datetime: 'Sana / Vaqt',
    ev_col_hall_table: 'Zal / Stol',
    no_events_yet: 'Hozircha tadbirlar yoq.',
    dishes_count: '{count} taom',
    dish_count_one: '1 taom',
    pcs_total: 'jami {count} dona',
    hidden_label: 'Yashirin',
    do_not_show: 'Korsatilmasin',
    show_subcategory: 'Korsatish',
    disable_subcategories: 'Subkategoriyalarni ochirish',
    disable_subcategories_help: 'Asosiy tugma — yoqilganda subkategoriyalar hamma joyda ochiriladi: menyu taomlaridagi Subkategoriya ustuni yashiriladi va katering saytida quyidagi alohida subkategoriyalardan qatiy nazar subkategoriya sarlavhalari korsatilmaydi.',
    subcategories_enabled: 'Subkategoriyalar yoniq',
    subcategories_disabled: 'Subkategoriyalar ochirilgan',
    more: 'Yana',
    settings: 'Sozlamalar',
    excluded_categories: 'Chiqarib tashlangan taom turkumlari',
    excluded_categories_help: 'Belgilangan turkumlar mavjud emas va hamma joyda — menyu, stol toifalari va rasmlarda yashiriladi. Ulardagi taomlar saqlanib qoladi va belgini olib tashlasangiz qayta paydo bo\'ladi.',
    excluded_count: '{count} ta turkum chiqarib tashlangan',
    nothing_excluded: 'Hech qanday turkum chiqarib tashlanmagan — hammasi mavjud.',
    save_settings: 'Sozlamalarni saqlash',
    settings_saved: 'Sozlamalar saqlandi.',
    settings_save_failed: 'Sozlamalarni saqlab bo\'lmadi.',
    select_hall: '-- Zalni tanlang --',
    menu_management: 'Menyu boshqaruvi',
    create_menu_item: 'Menyu elementi yaratish',
    name: 'Nomi',
    name_optional: 'Nomi (ixtiyoriy)',
    blank_uses_company_name: 'Kompaniya nomidan foydalanish uchun bosh qoldiring.',
    description: 'Tavsif',
    category: 'Kategoriya',
    price: 'Narx',
    photo_url: 'Rasm URL',
    create: 'Yaratish',
    update: 'Yangilash',
    delete: 'O\'chirish',
    deleting: 'O\'chirilmoqda...',
    active: 'Faol',
    inactive: 'Faol emas',
    cold_appetizers: 'Sovuq zakuskalar',
    hot_appetizers: 'Issiq zakuskalar',
    your_selection: 'Sizning tanlovingiz',
    assorted: 'Assorti',
    salads: 'Salatlar',
    first_course: 'Birinchi taom',
    second_course: 'Ikkinchi taom',
    third_course: 'Uchinchi taom',
    drinks: 'Ichimliklar',
    sweets: 'Desertlar',
    fruits: 'Mevalar',
    soups: 'Sho\'rvalar',
    pizza: 'Pitsa',
    grill: 'Mangal',
    pastry: 'Pishiriqlar',
    beer_snacks: 'Pivoga gazaklar',
    dessert: 'Desert',
    lamb_dishes: 'Qo\'y go\'shti taomlari',
    beef_dishes: 'Mol go\'shti taomlari',
    chicken_dishes: 'Tovuq taomlari',
    side_dishes: 'Garnirlar',
    pasta: 'Pasta',
    soft_drinks: 'Salqin ichimliklar',
    steaks: 'Steyklar',
    energy_drinks: 'Energetik ichimliklar',
    salads_oil: 'Yog\' asosidagi salatlar',
    salads_mayo: 'Mayonez asosidagi salatlar',
    coffee: 'Kofe',
    sushi_rolls: 'Sushi va rollar',
    dried_fruits: 'Quritilgan mevalar',
    candies: 'Konfetlar',
    alcohol: 'Alkogol',
    lemonades: 'Limonadlar',
    non_alcoholic_cocktails: 'Alkogolsiz kokteyllar',
    alcoholic_cocktails: 'Alkogolли kokteyllar',
    milkshakes: 'Sut kokteyllari',
    tea_menu: 'Choy kartasi',
    fresh_juices: 'Yangi siqilgan sharbatlar',
    liqueurs: 'Likörlar',
    filter_all: 'Hammasi',
    food_package: 'Ovqat paketi',
    included_with_table: 'Stolingizga kiritilgan',
    servings_per_table: 'Har bir stol uchun porsiya',
    courses: 'Birinchi va ikkinchi taom',
    additional: 'Qo\'shimcha',
    additional_management: 'Qo\'shimcha taomlar',
    additional_help: 'Har bir taom holatini belgilang: «Pullik» — planshetda pullik qo\'shimcha taom sifatida ko\'rsatadi, «Bepul» — mehmonlarga kiritilgan taomlarni bepul almashtirishga ruxsat beradi, «Ko\'rsatilmasin» — ikkalasidan ham yashiradi.',
    status_dont_show: 'Ko\'rsatilmasin',
    status_free: 'Bepul',
    status_paid: 'Pullik',
    swap_free: 'Bepul almashtirish',
    choose_replacement: 'Almashtirishni tanlang',
    included_default: 'kiritilgan',
    revert_to_default: 'Standart taomga qaytarish',
    table_type: 'Stol turi',
    table_type_adult: 'Kattalar stoli',
    table_type_children: 'Bolalar stoli',
    children_table: 'Bolalar stoli',
    add_children_table: 'Bolalar stolini qoshish',
    children_table_included: 'Bolalar stoli qoshildi',
    children_count: 'Bolalar soni',
    subcategories: 'Quyi toifalar',
    subcategory: 'Quyi toifa',
    subcategories_help: 'Katering saytida har bir taom toifasini bolimlarga ajratish uchun quyi toifalar yarating.',
    create_subcategory: 'Quyi toifa yaratish',
    subcategory_name: 'Quyi toifa nomi',
    add_subcategory: 'Quyi toifa qoshish',
    no_subcategories_yet: 'Hali quyi toifalar yoq.',
    no_subcategory: 'Quyi toifasiz',
    delete_subcategory_confirm: 'Bu quyi toifani ochirishni tasdiqlaysizmi?',
    other: 'Boshqa',
    show_on_tablet: 'Planshetda ko\'rsatilgan',
    bestseller: 'Xit',
    bestsellers_only: 'Faqat xitlar',
    out_of_stock: 'Mavjud emas',
    attach_photo: 'Rasm biriktirish',
    shown: 'Ko\'rsatilgan',
    hidden: 'Yashirilgan',
    discount: 'Chegirma',
    discount_percent: 'Chegirma (%)',
    apply_discount: 'Chegirma qo\'llash',
    original_price: 'Chegirmasiz narx',
    discounted_price: 'Chegirmali narx',
    no_additional_dishes: 'Hozircha qo\'shimcha taomlar yo\'q. Ularni Menyu sahifasida qo\'shing.',
    table_categories_management: 'Stol kategoriyalari boshqaruvi',
    create_table_category: 'Stol kategoriyasini yaratish',
    seating_capacity: 'Sig\'im',
    meal_package: 'Ovqat paketi',
    rate_per_person: 'Bir kishi uchun narx',
    table_category_name_placeholder: 'masalan, 2 kishilik stol',
    photo_url_optional: 'Rasm URL (ixtiyoriy)',
    description_optional: 'Tavsif (ixtiyoriy)',
    required: 'Majburiy',
    photo_url_placeholder: 'https://example.com/image.jpg',
    create_category: 'Kategoriya yaratish',
    failed_to_create_category: 'Kategoriyani yaratib bo\'lmadi.',
    loading_table_categories: 'Stol kategoriyalari yuklanmoqda...',
    failed_to_load_table_categories: 'Stol kategoriyalarini yuklab bo\'lmadi.',
    all_categories: 'Barcha kategoriyalar',
    no_table_categories_yet: 'Hali stol kategoriyalari yo\'q.',
    capacity: 'Sig\'im',
    meal: 'Ovqat',
    rate: 'Stavka',
    rate_dollar: 'Stavka ($)',
    saving: 'Saqlanmoqda...',
    save: 'Saqlash',
    edit: 'Tahrirlash',
    halls_management: 'Zallar boshqaruvi',
    create_hall: 'Zal yaratish',
    hall_name_placeholder: 'masalan, Asosiy zal',
    create_hall_button: 'Zal yaratish',
    failed_to_create_hall: 'Zalni yaratib bo\'lmadi.',
    loading_halls: 'Zallar yuklanmoqda...',
    failed_to_load_halls: 'Zallarni yuklab bo\'lmadi.',
    all_halls: 'Barcha zallar',
    no_halls_yet: 'Hali zallar yo\'q.',
    hall_capacity: 'Sig\'im',
    hall_description: 'Tavsif',
    hall_photo_url: 'Rasm URL',
    hall_active: 'Faol',
    hall_inactive: 'Faol emas',
    photos: 'Rasmlar',
    photo_management: 'Rasmlarni boshqarish',
    upload_photos: 'Rasmlarni yuklash',
    photo_category: 'Rasmlar kategoriyasi',
    menu_photos: 'Menyu rasmlari',
    hall_photos: 'Zal rasmlari',
    table_photos: 'Stol rasmlari',
    table_categories: 'Stol kategoriyalari',
    select_table: 'Bu stolni tanlash',
    person: 'kishi',
    dish_category: 'Taom kategoriyasi',
    select_upload_files: 'Fayllarni tanlang',
    uploading: 'Yuklanmoqda...',
    upload_photos_help: 'Menyu, zallar va stollar uchun rasmlarni boshqarish uchun rasmlarni yükleyin. Maksimal 5 MB har bir fayl.',
    loading_photos: 'Rasmlar yuklanmoqda...',
    failed_load_photos: 'Rasmlarni yuklab bolmadi.',
    no_photos_uploaded: 'Hali rasmlar yuklenmagan.',
    confirm_delete_photo: 'Siz bu rasmni ochirib tashlamoqchimisiz?',
    select_menu_photo: 'Menyu elementi uchun rasm tanlang',
    select_hall_photo: 'Zal uchun rasm tanlang',
    select_table_photo: 'Stol kategoriyasi uchun rasm tanlang',
    selected_photo: 'Tanlangan',
    clear_selection: 'Tozalash',
    search_event_by_id: 'ID bo\'yicha tadbir qidirish',
    enter_event_id: 'Tadbir ID sini kiriting',
    search: 'Qidirish',
    search_olog_n: 'Qidirish',
    event_not_found: '{id} ID li tadbir topilmadi',
    search_result: 'Qidiruv natijasi',
    no_events_loaded: 'Tadbirlar yuklanmagan',
    start_new_booking: 'Yangi bron',
    submitting: 'Yuborilmoqda...',
    event_create_error: 'Tadbir yaratib bo\'lmadi. Qayta urinib ko\'ring.',
    notes_placeholder: 'Maxsus so\'rovlar yoki izohlar...',
    event_date: 'Tadbir sanasi',
    event_time: 'Tadbir vaqti',
    select_restaurant: 'Restoran tanlang',
    my_restaurants: 'Mening restoranlarim',
    restaurants_management: 'Mening restoranlarim',
    create_restaurant: 'Restoran yaratish',
    restaurant_name: 'Restoran nomi',
    restaurant_address: 'Manzil',
    restaurant_logo_url: 'Logo URL',
    restaurant_name_placeholder: 'masalan, Madinabek Banket',
    restaurant_address_placeholder: 'masalan, Asosiy ko\'cha 12, Toshkent',
    no_restaurants_yet: 'Hali restoranlar yo\'q. Birinchisini yarating.',
    loading_restaurants: 'Restoranlar yuklanmoqda...',
    failed_load_restaurants: 'Restoranlarni yuklab bo\'lmadi.',
    confirm_delete_restaurant: 'Siz bu restoranni o\'chirmoqchimisiz?',
    users: 'Foydalanuvchilar',
    users_management: 'Foydalanuvchilarni boshqarish',
    create_user: 'Foydalanuvchi yaratish',
    user_role: 'Rol',
    role_owner: 'Egasi',
    role_admin: 'Administrator',
    role_employee: 'Xodim',
    confirm_delete_user: 'Siz bu foydalanuvchini o\'chirmoqchimisiz?',
    no_users_yet: 'Hali foydalanuvchilar yo\'q.',
    loading_users: 'Foydalanuvchilar yuklanmoqda...',
    failed_load_users: 'Foydalanuvchilarni yuklab bo\'lmadi.',
    change_role: 'Rolni o\'zgartirish',
    password: 'Parol',
    event_type_reservation: 'Bron',
    event_type_banquet: 'Banket',
    event_type_wedding: 'To\'y',
    event_type_birthday: 'Tug\'ilgan kun',
    event_type_private_party: 'Xususiy ziyofat',
    event_type_corporate: 'Korporativ',
    event_type_fotiha_tui: 'Fotiha Tuyi',
    event_type_nachor_oshi: 'Nahor Oshi',
    birthday_person_name: 'Tug\'ilgan kun egasining ismi',
    birthday_person_name_placeholder: 'Ism va familiya',
    bride_name: 'Kelinchak ismi',
    groom_name: 'Kuyov ismi',
    bride_groom_name_placeholder: 'Ism va familiya',
    honoree_person_name: 'Ism',
    honoree_person_name_placeholder: 'Ism va familiya',
    sign_in: 'Kirish',
    create_account: 'Hisob yaratish',
    login_subtitle: 'Tadbirlar va menyuni boshqarish uchun kiring',
    register_subtitle: 'Restoran egasi hisobini yarating',
    username: 'Foydalanuvchi nomi',
    username_placeholder: 'Foydalanuvchi nomini kiriting',
    username_min_length: 'Kamida 3 ta belgi',
    restaurant_field_label: 'Restoran',
    restaurant_field_placeholder: 'Restoran nomingiz',
    restaurant_required: 'Restoran nomi majburiy',
    password_enter_placeholder: 'Parolni kiriting',
    password_create_placeholder: 'Kuchli parol yarating',
    signing_in: 'Kirilmoqda...',
    creating_account: 'Hisob yaratilmoqda...',
    first_admin_note: 'Birinchi ro\'yxatdan o\'tgan admin har doim kira oladi. Keyingi ro\'yxatdan o\'tishlar server sozlamasini talab qiladi.',
    confirm_delete_event: '{name} uchun tadbirni o\'chirish kerakmi?',
    pw_very_weak: 'Juda zaif',
    pw_weak: 'Zaif',
    pw_fair: 'O\'rtacha',
    pw_good: 'Yaxshi',
    pw_strong: 'Kuchli',
    pw_very_strong: 'Juda kuchli',
    pw_req_length: 'Kamida 8 ta belgi',
    pw_req_upper: 'Bir bosh harf',
    pw_req_lower: 'Bir kichik harf',
    pw_req_number: 'Bir raqam',
    owner_cabinet: 'Egasi kabineti',
    companies: 'Kompaniyalar',
    new_company: 'Yangi kompaniya',
    company_name: 'Kompaniya nomi',
    logo_url: 'Logo URL',
    logo: 'Logotip',
    logo_url_hint: 'Logo URL (masalan /uploads/logo.png)',
    add: 'Qo\'shish',
    adding: 'Qo\'shilmoqda...',
    add_restaurant_to: '{name} ga restoran qo\'shish',
    company_logo_used: 'Kompaniya logotipi avtomatik ishlatiladi — alohida restoran logotipi kerak emas.',
    restaurants_in: '{name} dagi restoranlar',
    no_companies_yet: 'Hali kompaniyalar yo\'q. Yuqorida birinchisini yarating.',
    all_users: 'Barcha foydalanuvchilar',
    select_restaurant_dash: '— Restoran tanlang —',
    restaurant_manager_needs_restaurant: 'Restoran menejeri restoranga biriktirilishi kerak; keyin uning tadbirlari xarajatlar hisobiga tushadi.',
    administrator_role: 'Administrator',
    employee_role: 'Xodim',
    kitchen_role: 'Oshxona',
    owner_role: 'Egasi',
    chief_admin_role: 'Bosh administrator',
    manager_role: 'Menejer',
    catering_admin_role: 'Food Admin',
    restaurant_manager_role: 'Restoran menejeri',
    expense_ledger: 'Xarajatlar daftari',
    expense_ledger_help: 'Kunlik ajratilgan mablag, mahsulot va ish haqi xarajatlarini hisobga oling.',
    select_date: 'Sanani tanlang',
    add_day: 'Kun qoshish',
    no_days_yet: 'Hali kunlar qoshilmagan.',
    loading: 'Yuklanmoqda...',
    something_went_wrong: 'Nimadir notogri ketdi.',
    allocated_funds: 'Ajratilgan mablag',
    delete_day_confirm: 'Bu kun va uning barcha xarajatlari ochirilsinmi?',
    product_expenses: 'Mahsulot xarajatlari',
    employee_salaries: 'Xodimlar ish haqi',
    additional_expenses: 'Qoshimcha xarajatlar',
    amount_spent: 'Sarflangan',
    remaining: 'Qoldiq',
    budget: 'Byudjet',
    guests_total: 'Barcha mehmonlar uchun xarajat',
    product_name: 'Mahsulot',
    quantity: 'Miqdor',
    amount: 'Summa',
    employee_name: 'Xodim',
    note: 'Izoh',
    unit_kg: 'kg',
    unit_g: 'g',
    unit_l: 'l',
    unit_ml: 'ml',
    unit_pcs: 'dona',
    export_pdf: 'PDF eksport',
    older_day: 'Oldingi kun',
    newer_day: 'Keyingi kun',
    period_day: '1 kun',
    period_3_days: '3 kun',
    period_week: '1 hafta',
    period_2_weeks: '2 hafta',
    period_month: '1 oy',
    accounts: 'Hisoblar',
    accounts_help: 'Kunlarni korib chiqing, tugagan kunlarni yoping va PDF hisobotlarni yuklab oling.',
    close_day: 'Kunni yopish',
    closed_label: 'Yopilgan',
    close_day_confirm: 'Bu kun yopilsinmi? U PDF yuklashlardan chiqariladi.',
    date_from: 'Dan',
    date_to: 'Gacha',
    closed_excluded_note: 'Yopilgan kunlar hisobga olinmaydi.',
    pdf_days_label: 'Kunlar soni',
    day_report: 'Kun hisoboti',
    day_report_placeholder: 'Kun yakuni...',
    download_close_selected: 'Yuklab olish va yopish',
    reopen_day: 'Qayta ochish',
    reopen_day_confirm: 'Bu kun qayta ochilsinmi?',
    dept_nahor: 'Nahor',
    dept_fotiha: 'Fotiha',
    dept_tui: 'Toy',
    dept_others: 'Boshqalar',
    or: 'yoki',
    add_day_for_date: 'Sana uchun',
    create_in_advance: 'Oldindan yaratish',
    booking: 'Bron',
    booking_name: 'Bron nomi',
    event_notes: 'Tadbir izohlari',
    event_notes_placeholder: 'Ushbu bolim uchun izohlar...',
    download_selected: 'Tanlanganlarni yuklash',
    download_additional: 'Qoshimchani yuklash',
    go_to_ledger: 'Ozgartirish',
    additional_expenses_help: 'Asosiy xarajatlardan alohida boshqa kunlik xarajatlar.',
    delete_company_confirm: '«{name}» kompaniyasini va uning barcha restoranlarini o\'chirish?',
    delete_restaurant_confirm: '{name} ni o\'chirish? Barcha ma\'lumotlari yo\'qoladi.',
    delete_user_confirm: '{name} foydalanuvchini o\'chirish?',
    address: 'Manzil',
    welcome_title: 'Xush kelibsiz!',
    welcome_intro: 'Bugun sizni ko\'rganimizdan xursandmiz. Biz bilan yoqimli vaqt o\'tkazishingizni, qulay muhitdan zavqlanishingizni va har bir mehmonga g\'amxo\'rlik va e\'tibor bilan tayyorlangan taomlardan tatib ko\'rishingizni umid qilamiz.',
    welcome_help: 'Agar taom yoki ichimlik tanlashda yordam kerak bo\'lsa, xodimlarimiz har doim yordamga tayyor.',
    welcome_bon_appetit: 'Yoqimli dam olish va yoqimli ishtaha tilaymiz!',
    welcome_continue: 'Davom etish',
    calendar: 'Kalendar',
    no_halls_to_display: 'Zallar yo\'q. Avval zal yarating.',
    booked: 'Band',
    available: 'Bo\'sh',
    breakfast: 'Nonushta',
    lunch: 'Tushlik',
    dinner: 'Kechki ovqat',
    month_january: 'Yanvar',
    month_february: 'Fevral',
    month_march: 'Mart',
    month_april: 'Aprel',
    month_may: 'May',
    month_june: 'Iyun',
    month_july: 'Iyul',
    month_august: 'Avgust',
    month_september: 'Sentabr',
    month_october: 'Oktabr',
    month_november: 'Noyabr',
    month_december: 'Dekabr',
    weekday_mon: 'Du',
    weekday_tue: 'Se',
    weekday_wed: 'Cho',
    weekday_thu: 'Pa',
    weekday_fri: 'Ju',
    weekday_sat: 'Sh',
    weekday_sun: 'Ya',
    install_app: 'Ilovani o\'rnatish',
    install_app_desc: 'Tezroq foydalanish uchun ilovani bosh ekranga qo\'shing.',
    install_ios_hint: '«Ulashish» tugmasini bosing va «Bosh ekranga qo\'shish» ni tanlang.',
    later: 'Keyinroq',
    edit_credentials: 'Ma\'lumotlarni o\'zgartirish',
    new_username: 'Yangi login',
    new_password: 'Yangi parol',
    password_blank_keep: 'O\'zgartirmaslik uchun bo\'sh qoldiring',
    credentials_saved: 'Saqlandi',
    devices: 'Qurilmalar',
    devices_management: 'Qurilmalar va seanslar',
    about_us: 'Biz haqimizda',
    contact_us: 'Aloqa',
    our_menu: 'Bizning menyu',
    view_category: 'Ochish',
    back_to_menu: 'Menyuga qaytish',
    address_label: 'Manzil',
    no_dishes_in_category: 'Bu turkumda hozircha taomlar yo\'q.',
    catering_welcome: 'Xush kelibsiz! Menyumiz bilan tanishing, biz haqimizda bilib oling va biz bilan bog\'laning.',
    reviews: 'Sharhlar',
    arrangement: 'Joylashuv',
    arrangement_help: 'Kategoriyalar va taomlarni katering saytida ko\'rinadigan tartibda joylashtirish uchun sudrab oling. Eng ko\'p sotiladiganlar har doim o\'z kategoriyasining yuqorisida qoladi.',
    arrangement_admin_help: 'Menyu kategoriyalari, taomlar va stol toifalarining ko\'rsatilish tartibini belgilang. O\'zgarishlar planshet, ommaviy sayt va tanlash ekranlarida qo\'llaniladi.',
    arrangement_tc_help: 'Stol toifalarini tanlash ekranlari va ommaviy saytda ko\'rsatiladigan tartibni belgilash uchun sudrab oling.',
    arrangement_categories: 'Kategoriyalar tartibi',
    arrangement_dishes: 'Ushbu kategoriyadagi taomlar',
    arrangement_saved: 'Joylashuv saqlandi',
    arrangement_save_failed: 'Joylashuvni saqlab bo\'lmadi',
    save_arrangement: 'Joylashuvni saqlash',
    move_up: 'Yuqoriga',
    move_down: 'Pastga',
    no_dishes: 'Taomlar yo\'q',
    our_history: 'Bizning tariximiz',
    phone: 'Telefon',
    email: 'Email',
    leave_a_review: 'Sharh qoldirish',
    your_name: 'Ismingiz',
    your_rating: 'Bahoyingiz',
    your_review: 'Sharhingiz',
    submit_review: 'Sharh yuborish',
    review_thanks: 'Rahmat! Sharhingiz moderatsiyadan keyin paydo bo\'ladi.',
    no_reviews_yet: 'Hozircha sharhlar yo\'q. Birinchi bo\'ling!',
    back_to_halls: 'Zallarga qaytish',
    view_hall: 'Zalni ochish',
    hall_gallery: 'Galereya',
    background_photo: 'Fon rasmi',
    background_photo_help: 'Ommaviy katering saytingiz foni sifatida ko\'rsatiladi.',
    manage_halls: 'Zallar',
    hall_info_help: 'Zallar va ularning rasmlari ommaviy saytda ko\'rinadi.',
    add_hall: 'Zal qo\'shish',
    no_halls: 'Hozircha zallar yo\'q.',
    add_photo: 'Rasm qo\'shish',
    seats: 'o\'rin',
    restaurant_info: 'Restoran ma\'lumotlari',
    restaurant_info_help: 'Bu ma\'lumot ommaviy saytda ko\'rsatiladi.',
    history_label: 'Tarix / Biz haqimizda',
    save_info: 'Saqlash',
    moderate_reviews: 'Sharhlar',
    approve: 'Tasdiqlash',
    unapprove: 'Yashirish',
    approved: 'Tasdiqlangan',
    pending_moderation: 'Kutilmoqda',
    no_reviews_to_moderate: 'Hozircha sharhlar yo\'q.',
    devices_help: 'Bular hozir hisobingizga kirgan qurilmalar.',
    this_device: 'Ushbu qurilma',
    disconnect: 'Uzish',
    last_active: 'Oxirgi faollik',
    signed_in: 'Kirilgan',
    no_devices: 'Faol qurilmalar yo\'q.',
    unknown_device: 'Nomaʼlum qurilma',
    confirm_disconnect_device: 'Ushbu qurilmani uzasizmi? Seans tugatiladi.',
    view_tablet_menu: 'Menyuni ko\'rish',
    choose_restaurant_to_view: 'Restoranni tanlang',
    view_only_mode: 'Faqat ko\'rish rejimi',
    no_restaurants_available: 'Restoranlar yo\'q.',
    choose_first_course: 'Birinchi taomni tanlang',
    choose_hot_appetizers: 'Issiq zakuskalarni tanlang',
    change_hot_appetizers: 'Issiq zakuskalarni ozgartirish',
    up_to_two: '2 tagacha',
    choose_second_course: 'Ikkinchi taomni tanlang',
    choose_third_course: 'Uchinchi taomni tanlang',
    multi_select: 'bir nechta tanlov',
    manager_portal: 'Menejer portali',
    flyers: 'Flayerlar',
    invitations: 'Taklifnomalar',
    new_invitation: 'Yangi taklifnoma',
    no_invitations_yet: 'Hozircha taklifnomalar yoq.',
    responses: 'Javoblar',
    restaurant_events: 'Restoran tadbirlari',
    all_restaurants: 'Barcha restoranlar',
    no_events: 'Tadbirlar yo\'q.',
    back: 'Orqaga',
    designer: 'Dizayner',
    block_designer_flyer: 'Flayer dizayneri',
    block_designer_invitation: 'Taklifnoma dizayneri',
    add_block: 'Blok qoshish',
    choose_block: 'Blokni tanlang',
    block_settings: 'Blok sozlamalari',
    theme_settings: 'Mavzu',
    preview: 'Korib chiqish',
    publish: 'Chop etish',
    published_label: 'Chop etilgan',
    save_changes: 'Ozgarishlarni saqlash',
    create_project: 'Yaratish',
    save_as_template: 'Shablon sifatida saqlash',
    template_saved: 'Shablon saqlandi',
    template_name: 'Shablon nomi',
    blank: 'Bosh',
    start_blank: 'Boshdan boshlash',
    my_templates: 'Mening shablonlarim',
    ready_made: 'Tayyor',
    no_templates: 'Hozircha saqlangan shablonlar yoq.',
    delete_block: 'Ochirish',
    duplicate_block: 'Nusxalash',
    animation: 'Animatsiya',
    duration_ms: 'Davomiyligi (ms)',
    delay_ms: 'Kechikish (ms)',
    accent_color: 'Aksent rangi',
    background_color: 'Fon rangi',
    tablet_theme: 'Planshet ranglari',
    tablet_theme_help: 'Mehmonlar planshetdagi menyu va yakuniy sahifalarda koradigan aksent va fon ranglarini belgilang.',
    reset_theme: 'Standartga qaytarish',
    trail: 'Kursor izi',
    trail_color: 'Iz rangi',
    music: 'Fon musiqasi',
    add_item: 'Qoshish',
    add_row: 'Qator qoshish',
    empty_design: 'Hozircha bloklar yoq — "Blok qoshish" tugmasini bosing.',
    block_hero: 'Muqova',
    block_heading: 'Sarlavha',
    block_text: 'Matn',
    block_image: 'Rasm',
    block_button: 'Tugma',
    block_countdown: 'Taymer',
    block_timing: 'Dastur',
    block_gallery: 'Galereya',
    block_menu: 'Menyu',
    block_socials: 'Ijtimoiy tarmoqlar',
    block_contacts: 'Kontaktlar',
    block_rsvp: 'Tasdiqlash',
    block_map: 'Xarita',
    block_promo: 'Promo',
    block_divider: 'Ajratgich',
    bf_title: 'Sarlavha',
    bf_subtitle: 'Quyi sarlavha',
    bf_image: 'Rasm',
    bf_text: 'Matn',
    bf_align: 'Tekislash',
    bf_label: 'Yozuv',
    bf_action: 'Amal',
    bf_datetime: 'Sana va vaqt',
    bf_gallery: 'Galereya elementlari',
    bf_timing: 'Dastur qatorlari',
    bf_menu: 'Menyu taomlari',
    bf_socials: 'Havolalar',
    bf_phone: 'Telefon',
    bf_telegram: 'Telegram havolasi',
    bf_instagram: 'Instagram havolasi',
    bf_address: 'Manzil',
    bf_code: 'Promokod',
    bf_rounded: 'Yumaloq burchaklar',
    align_left: 'Chap',
    align_center: 'Markaz',
    align_right: 'Ong',
    action_link: 'Havola',
    action_phone: 'Telefon',
    action_telegram: 'Telegram',
    action_map: 'Xarita (Yandex)',
    action_value: 'Qiymat',
  }
} as const;

type TranslationKey = keyof typeof resources.en;

export type { TranslationKey };

export function translate(key: TranslationKey, locale: Locale = defaultLocale, params?: Record<string, string | number>): string {
  const localeResources = (resources[locale] ?? resources[defaultLocale]) as Record<TranslationKey, string>;
  const fallbackResources = resources[defaultLocale] as Record<TranslationKey, string>;
  let value = localeResources[key] ?? fallbackResources[key] ?? key;

  if (params) {
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      value = value.replace(new RegExp(`{${paramKey}}`, 'g'), String(paramValue));
    });
  }

  return value;
}

export function createTranslator(locale: Locale) {
  return (key: TranslationKey, params?: Record<string, string | number>) => translate(key, locale, params);
}
